// Code generated by ogen, DO NOT EDIT.

package vantaapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AddControlFromLibraryOperation:                   []string{},
	AddControlToTrustCenterOperation:                 []string{},
	AddDiscoveredVendorToManagedOperation:            []string{},
	AddDocumentToControlOperation:                    []string{},
	AddTestToControlOperation:                        []string{},
	AddTrustCenterControlCategoryOperation:           []string{},
	AddTrustCenterViewerOperation:                    []string{},
	ApproveQuestionnaireOperation:                    []string{},
	ApproveTrustCenterAccessRequestOperation:         []string{},
	CancelRiskScenarioApprovalRequestOperation:       []string{},
	CompleteQuestionnaireOperation:                   []string{},
	CreateCustomerTrustAccountOperation:              []string{},
	CreateDocumentOperation:                          []string{},
	CreateFileQuestionnaireOperation:                 []string{},
	CreateLinkForDocumentOperation:                   []string{},
	CreateQuestionnaireExportOperation:               []string{},
	CreateRiskScenarioOperation:                      []string{},
	CreateTrustCenterFaqOperation:                    []string{},
	CreateTrustCenterResourceOperation:               []string{},
	CreateTrustCenterSubprocessorOperation:           []string{},
	CreateTrustCenterSubscriberOperation:             []string{},
	CreateTrustCenterSubscriberGroupOperation:        []string{},
	CreateTrustCenterUpdateOperation:                 []string{},
	CreateVendorOperation:                            []string{},
	CreateVendorFindingOperation:                     []string{},
	CreateWebsiteQuestionnaireOperation:              []string{},
	DeactivateTestEntityOperation:                    []string{},
	DeleteByIdOperation:                              []string{},
	DeleteControlOperation:                           []string{},
	DeleteDocumentOperation:                          []string{},
	DeleteDocumentForcontrolOperation:                []string{},
	DeleteFileForDocumentOperation:                   []string{},
	DeleteFindingByIdOperation:                       []string{},
	DeleteLinkForDocumentOperation:                   []string{},
	DeleteQuestionnaireOperation:                     []string{},
	DeleteSecurityReviewDocumentByIdOperation:        []string{},
	DeleteTestForControlOperation:                    []string{},
	DeleteTrustCenterControlOperation:                []string{},
	DeleteTrustCenterControlCategoryOperation:        []string{},
	DeleteTrustCenterFaqOperation:                    []string{},
	DeleteTrustCenterResourceOperation:               []string{},
	DeleteTrustCenterSubprocessorOperation:           []string{},
	DeleteTrustCenterSubscriberOperation:             []string{},
	DeleteTrustCenterSubscriberGroupOperation:        []string{},
	DeleteTrustCenterUpdateOperation:                 []string{},
	DenyTrustCenterAccessRequestOperation:            []string{},
	GetConnectedIntegrationOperation:                 []string{},
	GetControlOperation:                              []string{},
	GetCustomerTrustAccountOperation:                 []string{},
	GetDocumentOperation:                             []string{},
	GetFrameworkOperation:                            []string{},
	GetGroupOperation:                                []string{},
	GetMonitoredComputerOperation:                    []string{},
	GetPolicyOperation:                               []string{},
	GetQuestionnaireOperation:                        []string{},
	GetQuestionnaireExportOperation:                  []string{},
	GetResourceKindDetailsOperation:                  []string{},
	GetRiskScenarioOperation:                         []string{},
	GetSecurityReviewDocumentsOperation:              []string{},
	GetSecurityReviewsByIdOperation:                  []string{},
	GetSecurityReviewsByVendorIdOperation:            []string{},
	GetTestOperation:                                 []string{},
	GetTestEntitiesOperation:                         []string{},
	GetTrustCenterOperation:                          []string{},
	GetTrustCenterAccessRequestOperation:             []string{},
	GetTrustCenterControlOperation:                   []string{},
	GetTrustCenterControlCategoriesOperation:         []string{},
	GetTrustCenterControlCategoryOperation:           []string{},
	GetTrustCenterFaqOperation:                       []string{},
	GetTrustCenterResourceOperation:                  []string{},
	GetTrustCenterResourceMediaOperation:             []string{},
	GetTrustCenterSubprocessorOperation:              []string{},
	GetTrustCenterSubscriberOperation:                []string{},
	GetTrustCenterSubscriberGroupOperation:           []string{},
	GetTrustCenterUpdateOperation:                    []string{},
	GetTrustCenterViewerOperation:                    []string{},
	GetUploadedfileMediaOperation:                    []string{},
	GetVendorOperation:                               []string{},
	GetVulnerabilityOperation:                        []string{},
	GetVulnerableAssetOperation:                      []string{},
	ListConnectedIntegrationsOperation:               []string{},
	ListControlsOperation:                            []string{},
	ListControlsForDocumentOperation:                 []string{},
	ListControlsForFrameworkOperation:                []string{},
	ListCustomerTrustAccountsOperation:               []string{},
	ListDiscoveredVendorsOperation:                   []string{},
	ListDocumentsOperation:                           []string{},
	ListDocumentsForControlOperation:                 []string{},
	ListFilesForDocumentOperation:                    []string{},
	ListFrameworksOperation:                          []string{},
	ListLibraryControlsOperation:                     []string{},
	ListLinksForDocumentOperation:                    []string{},
	ListMonitoredComputersOperation:                  []string{},
	ListPersonGroupsOperation:                        []string{},
	ListPoliciesOperation:                            []string{},
	ListQuestionnairesOperation:                      []string{},
	ListResourceKindSummariesOperation:               []string{},
	ListRiskScenarioOperation:                        []string{},
	ListTestsOperation:                               []string{},
	ListTestsForControlOperation:                     []string{},
	ListTrustCenterAccessRequestsOperation:           []string{},
	ListTrustCenterControlsOperation:                 []string{},
	ListTrustCenterFaqsOperation:                     []string{},
	ListTrustCenterHistoricalAccessRequestsOperation: []string{},
	ListTrustCenterResourcesOperation:                []string{},
	ListTrustCenterSubprocessorsOperation:            []string{},
	ListTrustCenterSubscriberGroupsOperation:         []string{},
	ListTrustCenterSubscribersOperation:              []string{},
	ListTrustCenterUpdatesOperation:                  []string{},
	ListTrustCenterViewersOperation:                  []string{},
	ListVendorDocumentsOperation:                     []string{},
	ListVendorFindingsOperation:                      []string{},
	ListVendorRiskAttributesOperation:                []string{},
	ListVendorsOperation:                             []string{},
	ListVulnerabilitiesOperation:                     []string{},
	ListVulnerabilityRemediationsOperation:           []string{},
	ListVulnerableAssetsOperation:                    []string{},
	ReactivateTestEntityOperation:                    []string{},
	RemoveTrustCenterViewerOperation:                 []string{},
	SendNotificationsToAllSubscribersOperation:       []string{},
	SendTrustCenterUpdateNotificationsOperation:      []string{},
	SetOwnerForControlOperation:                      []string{},
	SetOwnerForDocumentOperation:                     []string{},
	SetStatusForVendorOperation:                      []string{},
	SubmitDocumentCollectionOperation:                []string{},
	SubmitRiskForApprovalOperation:                   []string{},
	UpdateControlMetadataOperation:                   []string{},
	UpdateQuestionnaireOperation:                     []string{},
	UpdateResourceOperation:                          []string{},
	UpdateRiskScenarioOperation:                      []string{},
	UpdateTrustCenterControlCategoryOperation:        []string{},
	UpdateTrustCenterFaqOperation:                    []string{},
	UpdateTrustCenterResourceOperation:               []string{},
	UpdateTrustCenterSubprocessorOperation:           []string{},
	UpdateTrustCenterSubscriberGroupOperation:        []string{},
	UpdateTrustCenterUpdateOperation:                 []string{},
	UpdateVendorOperation:                            []string{},
	UpdateVendorFindingOperation:                     []string{},
	UploadDocumentForSecurityReviewOperation:         []string{},
	UploadDocumentToVendorOperation:                  []string{},
	UploadFileForDocumentOperation:                   []string{},
	UpsertGroupsForTrustCenterSubscriberOperation:    []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
