// Code generated by ogen, DO NOT EDIT.

package vantaapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddControlFromLibrary implements AddControlFromLibrary operation.
//
// Add a control from the Vanta library to your organization's controls.
//
// POST /controls/add-from-library
func (UnimplementedHandler) AddControlFromLibrary(ctx context.Context, req *AddControlFromLibraryInput) (r *Control, _ error) {
	return r, ht.ErrNotImplemented
}

// AddControlToTrustCenter implements AddControlToTrustCenter operation.
//
// Adds a control to a Trust Center.
//
// POST /trust-centers/{slugId}/controls
func (UnimplementedHandler) AddControlToTrustCenter(ctx context.Context, req *AddControlToTrustCenterInput, params AddControlToTrustCenterParams) (r *TrustCenterControl, _ error) {
	return r, ht.ErrNotImplemented
}

// AddDiscoveredVendorToManaged implements AddDiscoveredVendorToManaged operation.
//
// Add a discovered vendor to managed vendor.
//
// POST /discovered-vendors/{discoveredVendorId}/add-to-managed
func (UnimplementedHandler) AddDiscoveredVendorToManaged(ctx context.Context, params AddDiscoveredVendorToManagedParams) (r *Vendor, _ error) {
	return r, ht.ErrNotImplemented
}

// AddDocumentToControl implements AddDocumentToControl operation.
//
// Add a document to a control.
//
// POST /controls/{controlId}/add-document-to-control
func (UnimplementedHandler) AddDocumentToControl(ctx context.Context, req *AddControlDocumentMappingInput, params AddDocumentToControlParams) (r *AddDocumentToControlOK, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTestToControl implements AddTestToControl operation.
//
// Add a control to test mapping.
//
// POST /controls/{controlId}/add-test-to-control
func (UnimplementedHandler) AddTestToControl(ctx context.Context, req *AddControlTestMappingInput, params AddTestToControlParams) (r *AddTestToControlOK, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTrustCenterControlCategory implements AddTrustCenterControlCategory operation.
//
// Adds a control category to a Trust Center.
//
// POST /trust-centers/{slugId}/control-categories
func (UnimplementedHandler) AddTrustCenterControlCategory(ctx context.Context, req *AddOrEditTrustCenterControlCategoryInput, params AddTrustCenterControlCategoryParams) (r *TrustCenterControlCategory, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTrustCenterViewer implements AddTrustCenterViewer operation.
//
// Adds a viewer and grants them access to a Trust Center.
//
// POST /trust-centers/{slugId}/viewers
func (UnimplementedHandler) AddTrustCenterViewer(ctx context.Context, req *AddTrustCenterViewerInput, params AddTrustCenterViewerParams) (r *TrustCenterViewer, _ error) {
	return r, ht.ErrNotImplemented
}

// ApproveQuestionnaire implements ApproveQuestionnaire operation.
//
// Approve a questionnaire.
//
// POST /customer-trust/questionnaires/{questionnaireId}/approve
func (UnimplementedHandler) ApproveQuestionnaire(ctx context.Context, req *ApproveQuestionnaireRequest, params ApproveQuestionnaireParams) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// ApproveTrustCenterAccessRequest implements ApproveTrustCenterAccessRequest operation.
//
// Approves an access request on a Trust Center.
//
// POST /trust-centers/{slugId}/access-requests/{accessRequestId}/approve
func (UnimplementedHandler) ApproveTrustCenterAccessRequest(ctx context.Context, req *ApproveTrustCenterAccessRequestInput, params ApproveTrustCenterAccessRequestParams) error {
	return ht.ErrNotImplemented
}

// CancelRiskScenarioApprovalRequest implements CancelRiskScenarioApprovalRequest operation.
//
// Cancel approval request for a risk scenario.
//
// POST /risk-scenarios/{riskScenarioId}/cancel-approval-request
func (UnimplementedHandler) CancelRiskScenarioApprovalRequest(ctx context.Context, params CancelRiskScenarioApprovalRequestParams) (r *RiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteQuestionnaire implements CompleteQuestionnaire operation.
//
// Complete a questionnaire and optionally sync approved answers to the answer library.
// Transitions the questionnaire status to COMPLETE. If `shouldSyncApprovedToAnswerLibrary` is true
// (the default), approved answers are added to the answer library for future use. For
// non-English SPREADSHEET or DOCUMENT questionnaires, answer library sync will be ignored.
//
// POST /customer-trust/questionnaires/{questionnaireId}/complete
func (UnimplementedHandler) CompleteQuestionnaire(ctx context.Context, req *CompleteQuestionnaireRequest, params CompleteQuestionnaireParams) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCustomerTrustAccount implements CreateCustomerTrustAccount operation.
//
// Create a new customer trust account.
//
// POST /customer-trust/accounts
func (UnimplementedHandler) CreateCustomerTrustAccount(ctx context.Context, req *CreateCustomerTrustAccountInput) (r *CustomerTrustAccountVantaApi, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDocument implements CreateDocument operation.
//
// Create a custom document.
//
// POST /documents
func (UnimplementedHandler) CreateDocument(ctx context.Context, req *CreateDocumentInput) (r *Document, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFileQuestionnaire implements CreateFileQuestionnaire operation.
//
// Create a new file-based questionnaire from an uploaded file (.xlsx, .docx, .pdf).
//
// POST /customer-trust/questionnaires/file
func (UnimplementedHandler) CreateFileQuestionnaire(ctx context.Context, req *CreateFileQuestionnaireReq) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLinkForDocument implements CreateLinkForDocument operation.
//
// Create a link for a document.
//
// POST /documents/{documentId}/links
func (UnimplementedHandler) CreateLinkForDocument(ctx context.Context, req *CreateLinkForDocumentInput, params CreateLinkForDocumentParams) (r *UploadedLink, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateQuestionnaireExport implements CreateQuestionnaireExport operation.
//
// Creates an asynchronous export job for a questionnaire. The export processes in the background
// and typically completes within a few minutes depending on questionnaire size.
// Subscribe to the `v1.questionnaire.export-completed` and `v1.questionnaire.export-failed` webhook
// events to be notified when an export completes or fails.
// Use the returned `id` with the "getQuestionnaireExport" endpoint to retrieve the download URL once
// the export completes.
//
// POST /customer-trust/questionnaires/exports
func (UnimplementedHandler) CreateQuestionnaireExport(ctx context.Context, req *CustomerTrustCreateQuestionnaireExportInput) (r *CustomerTrustCreateQuestionnaireExportResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRiskScenario implements CreateRiskScenario operation.
//
// Create a new risk scenario.
//
// POST /risk-scenarios
func (UnimplementedHandler) CreateRiskScenario(ctx context.Context, req *CreateRiskScenarioInput) (r *RiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterFaq implements CreateTrustCenterFaq operation.
//
// Adds an FAQ to a Trust Center.
//
// POST /trust-centers/{slugId}/faqs
func (UnimplementedHandler) CreateTrustCenterFaq(ctx context.Context, req *AddOrEditTrustCenterFaqInput, params CreateTrustCenterFaqParams) (r *TrustCenterFaq, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterResource implements CreateTrustCenterResource operation.
//
// Adds a document to a Trust Center.
//
// POST /trust-centers/{slugId}/resources
func (UnimplementedHandler) CreateTrustCenterResource(ctx context.Context, req *CreateTrustCenterResourceReq, params CreateTrustCenterResourceParams) (r *TrustCenterResource, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterSubprocessor implements CreateTrustCenterSubprocessor operation.
//
// Adds a subprocessor to a Trust Center.
//
// POST /trust-centers/{slugId}/subprocessors
func (UnimplementedHandler) CreateTrustCenterSubprocessor(ctx context.Context, req *AddTrustCenterSubprocessorInput, params CreateTrustCenterSubprocessorParams) (r NilTrustCenterSubprocessor, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterSubscriber implements CreateTrustCenterSubscriber operation.
//
// Adds a subscriber to a Trust Center.
//
// POST /trust-centers/{slugId}/subscribers
func (UnimplementedHandler) CreateTrustCenterSubscriber(ctx context.Context, req *AddTrustCenterSubscriberInput, params CreateTrustCenterSubscriberParams) (r *TrustCenterSubscriber, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterSubscriberGroup implements CreateTrustCenterSubscriberGroup operation.
//
// Adds a subscriber group to a Trust Center.
//
// POST /trust-centers/{slugId}/subscriber-groups
func (UnimplementedHandler) CreateTrustCenterSubscriberGroup(ctx context.Context, req *CreateTrustCenterSubscriberGroupInput, params CreateTrustCenterSubscriberGroupParams) (r *TrustCenterSubscriberGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTrustCenterUpdate implements CreateTrustCenterUpdate operation.
//
// Adds an update to a Trust Center.
//
// POST /trust-centers/{slugId}/updates
func (UnimplementedHandler) CreateTrustCenterUpdate(ctx context.Context, req *AddTrustCenterUpdateInput, params CreateTrustCenterUpdateParams) (r *TrustCenterUpdateAPIResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVendor implements CreateVendor operation.
//
// Add vendor with metadata.
//
// POST /vendors
func (UnimplementedHandler) CreateVendor(ctx context.Context, req *CreateVendorInput) (r *Vendor, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVendorFinding implements CreateVendorFinding operation.
//
// Add vendor finding.
//
// POST /vendors/{vendorId}/findings
func (UnimplementedHandler) CreateVendorFinding(ctx context.Context, req *CreateFindingInput, params CreateVendorFindingParams) (r *VendorFinding, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebsiteQuestionnaire implements CreateWebsiteQuestionnaire operation.
//
// Create a new website-based questionnaire from a portal URL.
// The portal URL is used to fetch questionnaire content from the target website.
//
// POST /customer-trust/questionnaires/website
func (UnimplementedHandler) CreateWebsiteQuestionnaire(ctx context.Context, req *CreateWebsiteQuestionnaireInput) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// DeactivateTestEntity implements DeactivateTestEntity operation.
//
// Deactivates a single test item (test entity).
// There may be a delay in the deactivation of the test entity until the next test run.
// Use the /vulnerabilities/deactivate endpoint for vulnerabilities.
//
// POST /tests/{testId}/entities/{entityId}/deactivate
func (UnimplementedHandler) DeactivateTestEntity(ctx context.Context, req *DeactivateTestEntityReq, params DeactivateTestEntityParams) error {
	return ht.ErrNotImplemented
}

// DeleteById implements DeleteById operation.
//
// Deletes a vendor.
//
// DELETE /vendors/{vendorId}
func (UnimplementedHandler) DeleteById(ctx context.Context, params DeleteByIdParams) error {
	return ht.ErrNotImplemented
}

// DeleteControl implements DeleteControl operation.
//
// Delete a custom control or move a Vanta control back to the library.
//
// DELETE /controls/{controlId}
func (UnimplementedHandler) DeleteControl(ctx context.Context, params DeleteControlParams) error {
	return ht.ErrNotImplemented
}

// DeleteDocument implements DeleteDocument operation.
//
// Delete a document by ID.
//
// DELETE /documents/{documentId}
func (UnimplementedHandler) DeleteDocument(ctx context.Context, params DeleteDocumentParams) error {
	return ht.ErrNotImplemented
}

// DeleteDocumentForcontrol implements DeleteDocumentForcontrol operation.
//
// Remove a document by ID from a control.
//
// DELETE /controls/{controlId}/documents/{documentId}
func (UnimplementedHandler) DeleteDocumentForcontrol(ctx context.Context, params DeleteDocumentForcontrolParams) error {
	return ht.ErrNotImplemented
}

// DeleteFileForDocument implements DeleteFileForDocument operation.
//
// Delete a file for a document.
//
// DELETE /documents/{documentId}/uploads/{uploadedFileId}
func (UnimplementedHandler) DeleteFileForDocument(ctx context.Context, params DeleteFileForDocumentParams) error {
	return ht.ErrNotImplemented
}

// DeleteFindingById implements DeleteFindingById operation.
//
// Deletes a finding.
//
// DELETE /vendors/{vendorId}/findings/{findingId}
func (UnimplementedHandler) DeleteFindingById(ctx context.Context, params DeleteFindingByIdParams) error {
	return ht.ErrNotImplemented
}

// DeleteLinkForDocument implements DeleteLinkForDocument operation.
//
// Remove a link from a document.
//
// DELETE /documents/{documentId}/links/{linkId}
func (UnimplementedHandler) DeleteLinkForDocument(ctx context.Context, params DeleteLinkForDocumentParams) error {
	return ht.ErrNotImplemented
}

// DeleteQuestionnaire implements DeleteQuestionnaire operation.
//
// Delete a questionnaire by ID.
//
// DELETE /customer-trust/questionnaires/{questionnaireId}
func (UnimplementedHandler) DeleteQuestionnaire(ctx context.Context, params DeleteQuestionnaireParams) error {
	return ht.ErrNotImplemented
}

// DeleteSecurityReviewDocumentById implements DeleteSecurityReviewDocumentById operation.
//
// Delete a security review document.
//
// DELETE /vendors/{vendorId}/security-reviews/{securityReviewId}/documents/{documentId}
func (UnimplementedHandler) DeleteSecurityReviewDocumentById(ctx context.Context, params DeleteSecurityReviewDocumentByIdParams) error {
	return ht.ErrNotImplemented
}

// DeleteTestForControl implements DeleteTestForControl operation.
//
// Remove a control from test mapping.
//
// DELETE /controls/{controlId}/tests/{testId}
func (UnimplementedHandler) DeleteTestForControl(ctx context.Context, params DeleteTestForControlParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterControl implements DeleteTrustCenterControl operation.
//
// Removes a specific control from a Trust Center. This removes the control
// from all of the control categories that is in.
//
// DELETE /trust-centers/{slugId}/controls/{controlId}
func (UnimplementedHandler) DeleteTrustCenterControl(ctx context.Context, params DeleteTrustCenterControlParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterControlCategory implements DeleteTrustCenterControlCategory operation.
//
// Removes a control category from a Trust Center along with all of the
// controls in the category.
//
// DELETE /trust-centers/{slugId}/control-categories/{categoryId}
func (UnimplementedHandler) DeleteTrustCenterControlCategory(ctx context.Context, params DeleteTrustCenterControlCategoryParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterFaq implements DeleteTrustCenterFaq operation.
//
// Remove a specific FAQ from the Trust Center by ID.
//
// DELETE /trust-centers/{slugId}/faqs/{faqId}
func (UnimplementedHandler) DeleteTrustCenterFaq(ctx context.Context, params DeleteTrustCenterFaqParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterResource implements DeleteTrustCenterResource operation.
//
// Removes a specific document from a Trust Center.
//
// DELETE /trust-centers/{slugId}/resources/{resourceId}
func (UnimplementedHandler) DeleteTrustCenterResource(ctx context.Context, params DeleteTrustCenterResourceParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterSubprocessor implements DeleteTrustCenterSubprocessor operation.
//
// Removes a subprocessor from a Trust Center.
//
// DELETE /trust-centers/{slugId}/subprocessors/{subprocessorId}
func (UnimplementedHandler) DeleteTrustCenterSubprocessor(ctx context.Context, params DeleteTrustCenterSubprocessorParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterSubscriber implements DeleteTrustCenterSubscriber operation.
//
// Removes a subscriber from a Trust Center.
//
// DELETE /trust-centers/{slugId}/subscribers/{subscriberId}
func (UnimplementedHandler) DeleteTrustCenterSubscriber(ctx context.Context, params DeleteTrustCenterSubscriberParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterSubscriberGroup implements DeleteTrustCenterSubscriberGroup operation.
//
// Removes a subscriber group from a Trust Center.
//
// DELETE /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
func (UnimplementedHandler) DeleteTrustCenterSubscriberGroup(ctx context.Context, params DeleteTrustCenterSubscriberGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteTrustCenterUpdate implements DeleteTrustCenterUpdate operation.
//
// Removes an update from a Trust Center.
//
// DELETE /trust-centers/{slugId}/updates/{updateId}
func (UnimplementedHandler) DeleteTrustCenterUpdate(ctx context.Context, params DeleteTrustCenterUpdateParams) error {
	return ht.ErrNotImplemented
}

// DenyTrustCenterAccessRequest implements DenyTrustCenterAccessRequest operation.
//
// Denies an access request on a Trust Center.
//
// POST /trust-centers/{slugId}/access-requests/{accessRequestId}/deny
func (UnimplementedHandler) DenyTrustCenterAccessRequest(ctx context.Context, params DenyTrustCenterAccessRequestParams) error {
	return ht.ErrNotImplemented
}

// GetConnectedIntegration implements GetConnectedIntegration operation.
//
// Gets details for a specific integration by connection ID.
//
// GET /integrations/{integrationId}
func (UnimplementedHandler) GetConnectedIntegration(ctx context.Context, params GetConnectedIntegrationParams) (r *Integration, _ error) {
	return r, ht.ErrNotImplemented
}

// GetControl implements GetControl operation.
//
// Get a control by an ID.
//
// GET /controls/{controlId}
func (UnimplementedHandler) GetControl(ctx context.Context, params GetControlParams) (r *ControlDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCustomerTrustAccount implements GetCustomerTrustAccount operation.
//
// Get a specific customer trust account by ID.
//
// GET /customer-trust/accounts/{accountId}
func (UnimplementedHandler) GetCustomerTrustAccount(ctx context.Context, params GetCustomerTrustAccountParams) (r *CustomerTrustAccountVantaApi, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocument implements GetDocument operation.
//
// Get a document by ID.
//
// GET /documents/{documentId}
func (UnimplementedHandler) GetDocument(ctx context.Context, params GetDocumentParams) (r *DocumentDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFramework implements GetFramework operation.
//
// Get a framework by ID.
//
// GET /frameworks/{frameworkId}
func (UnimplementedHandler) GetFramework(ctx context.Context, params GetFrameworkParams) (r *FrameworkDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroup implements GetGroup operation.
//
// Get a group by ID.
//
// GET /groups/{groupId}
func (UnimplementedHandler) GetGroup(ctx context.Context, params GetGroupParams) (r *Group, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitoredComputer implements GetMonitoredComputer operation.
//
// Returns a monitored computer by ID.
//
// GET /monitored-computers/{computerId}
func (UnimplementedHandler) GetMonitoredComputer(ctx context.Context, params GetMonitoredComputerParams) (r *MonitoredComputer, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPolicy implements GetPolicy operation.
//
// Gets a policy by ID. Policy IDs can be found in Vanta in URL bar after /policies/.
//
// GET /policies/{policyId}
func (UnimplementedHandler) GetPolicy(ctx context.Context, params GetPolicyParams) (r *Policy, _ error) {
	return r, ht.ErrNotImplemented
}

// GetQuestionnaire implements GetQuestionnaire operation.
//
// Retrieve a questionnaire by ID.
//
// GET /customer-trust/questionnaires/{questionnaireId}
func (UnimplementedHandler) GetQuestionnaire(ctx context.Context, params GetQuestionnaireParams) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// GetQuestionnaireExport implements GetQuestionnaireExport operation.
//
// Retrieves the current status and result of a questionnaire export using the id received from
// either the POST /v1/customer-trust/questionnaires/exports endpoint or the v1.questionnaire.
// export-completed payload.
// This endpoint utilizes a dynamic response schema that changes based on the value of the status
// field:
// - pending: The export is currently in the queue or processing. Only base metadata is returned.
// - completed: The export finished successfully. The response expands to include completedAt and a
// downloadUrl. This pre-signed URL is valid for 24 hours; if it expires, simply call this endpoint
// again to retrieve a fresh, active link.
// - failed: The process encountered an error. The response expands to include failedAt and an
// errorMessage detailing the reason for failure.
// Developers should first check the status string before attempting to access result-specific fields
// like downloadUrl or errorMessage.
//
// GET /customer-trust/questionnaires/exports/{id}
func (UnimplementedHandler) GetQuestionnaireExport(ctx context.Context, params GetQuestionnaireExportParams) (r *CustomerTrustExportStatusResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceKindDetails implements GetResourceKindDetails operation.
//
// Gets details for a specific resource type (kind) such as S3Bucket or CloudwatchLogGroup.
//
// GET /integrations/{integrationId}/resource-kinds/{resourceKind}
func (UnimplementedHandler) GetResourceKindDetails(ctx context.Context, params GetResourceKindDetailsParams) (r *ResourceKindDetails, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRiskScenario implements GetRiskScenario operation.
//
// Get a risk scenario by ID (can be the Risk ID or the object ID).
//
// GET /risk-scenarios/{riskScenarioId}
func (UnimplementedHandler) GetRiskScenario(ctx context.Context, params GetRiskScenarioParams) (r *RiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecurityReviewDocuments implements GetSecurityReviewDocuments operation.
//
// Lists a security review's documents.
//
// GET /vendors/{vendorId}/security-reviews/{securityReviewId}/documents
func (UnimplementedHandler) GetSecurityReviewDocuments(ctx context.Context, params GetSecurityReviewDocumentsParams) (r *PaginatedResponseVendorDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecurityReviewsById implements GetSecurityReviewsById operation.
//
// Returns a security review.
//
// GET /vendors/{vendorId}/security-reviews/{securityReviewId}
func (UnimplementedHandler) GetSecurityReviewsById(ctx context.Context, params GetSecurityReviewsByIdParams) (r *SecurityReview, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecurityReviewsByVendorId implements GetSecurityReviewsByVendorId operation.
//
// Returns a vendor's security reviews.
//
// GET /vendors/{vendorId}/security-reviews
func (UnimplementedHandler) GetSecurityReviewsByVendorId(ctx context.Context, params GetSecurityReviewsByVendorIdParams) (r *PaginatedResponseSecurityReview, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTest implements GetTest operation.
//
// Gets a test by ID. Test IDs can be found in Vanta in URL bar after /tests/.
//
// GET /tests/{testId}
func (UnimplementedHandler) GetTest(ctx context.Context, params GetTestParams) (r *Test, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTestEntities implements GetTestEntities operation.
//
// Gets a list of tested items (entities) for a test by test ID. An entity is a tested item that can
// have its own outcome.
// For example, for a test that makes sure that all S3 buckets are versioned, an individual S3 bucket
// would be an entity.
//
// GET /tests/{testId}/entities
func (UnimplementedHandler) GetTestEntities(ctx context.Context, params GetTestEntitiesParams) (r *PaginatedResponseTestResourceEntity, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenter implements GetTrustCenter operation.
//
// Gets a Trust Center by slug ID.
//
// GET /trust-centers/{slugId}
func (UnimplementedHandler) GetTrustCenter(ctx context.Context, params GetTrustCenterParams) (r *TrustCenter, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterAccessRequest implements GetTrustCenterAccessRequest operation.
//
// Gets a specific access request for a Trust Center.
//
// GET /trust-centers/{slugId}/access-requests/{accessRequestId}
func (UnimplementedHandler) GetTrustCenterAccessRequest(ctx context.Context, params GetTrustCenterAccessRequestParams) (r *TrustCenterAccessRequest, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterControl implements GetTrustCenterControl operation.
//
// Gets a specific control on a Trust Center.
//
// GET /trust-centers/{slugId}/controls/{controlId}
func (UnimplementedHandler) GetTrustCenterControl(ctx context.Context, params GetTrustCenterControlParams) (r *TrustCenterControl, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterControlCategories implements GetTrustCenterControlCategories operation.
//
// Gets a list of control categories on a Trust Center.
//
// GET /trust-centers/{slugId}/control-categories
func (UnimplementedHandler) GetTrustCenterControlCategories(ctx context.Context, params GetTrustCenterControlCategoriesParams) (r *ArrayResponseTrustCenterControlCategory, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterControlCategory implements GetTrustCenterControlCategory operation.
//
// Gets a specific control category on a Trust Center.
//
// GET /trust-centers/{slugId}/control-categories/{categoryId}
func (UnimplementedHandler) GetTrustCenterControlCategory(ctx context.Context, params GetTrustCenterControlCategoryParams) (r *TrustCenterControlCategory, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterFaq implements GetTrustCenterFaq operation.
//
// Gets a specific FAQ on the Trust Center by ID.
//
// GET /trust-centers/{slugId}/faqs/{faqId}
func (UnimplementedHandler) GetTrustCenterFaq(ctx context.Context, params GetTrustCenterFaqParams) (r *TrustCenterFaq, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterResource implements GetTrustCenterResource operation.
//
// Gets a specific document on a Trust Center.
//
// GET /trust-centers/{slugId}/resources/{resourceId}
func (UnimplementedHandler) GetTrustCenterResource(ctx context.Context, params GetTrustCenterResourceParams) (r *TrustCenterResource, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterResourceMedia implements GetTrustCenterResourceMedia operation.
//
// Gets the actual given uploaded document for a Trust Center.
//
// GET /trust-centers/{slugId}/resources/{resourceId}/media
func (UnimplementedHandler) GetTrustCenterResourceMedia(ctx context.Context, params GetTrustCenterResourceMediaParams) (r *NodeJSReadableStream, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterSubprocessor implements GetTrustCenterSubprocessor operation.
//
// Gets a specific subprocessor on a Trust Center.
//
// GET /trust-centers/{slugId}/subprocessors/{subprocessorId}
func (UnimplementedHandler) GetTrustCenterSubprocessor(ctx context.Context, params GetTrustCenterSubprocessorParams) (r *TrustCenterSubprocessor, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterSubscriber implements GetTrustCenterSubscriber operation.
//
// Gets a specific subscriber on a Trust Center.
//
// GET /trust-centers/{slugId}/subscribers/{subscriberId}
func (UnimplementedHandler) GetTrustCenterSubscriber(ctx context.Context, params GetTrustCenterSubscriberParams) (r *TrustCenterSubscriber, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterSubscriberGroup implements GetTrustCenterSubscriberGroup operation.
//
// Get a subscriber group by ID.
//
// GET /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
func (UnimplementedHandler) GetTrustCenterSubscriberGroup(ctx context.Context, params GetTrustCenterSubscriberGroupParams) (r *TrustCenterSubscriberGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterUpdate implements GetTrustCenterUpdate operation.
//
// Gets a specific update on a Trust Center.
//
// GET /trust-centers/{slugId}/updates/{updateId}
func (UnimplementedHandler) GetTrustCenterUpdate(ctx context.Context, params GetTrustCenterUpdateParams) (r *TrustCenterUpdateAPIResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrustCenterViewer implements GetTrustCenterViewer operation.
//
// Gets a specific viewer for a Trust Center.
//
// GET /trust-centers/{slugId}/viewers/{viewerId}
func (UnimplementedHandler) GetTrustCenterViewer(ctx context.Context, params GetTrustCenterViewerParams) (r *TrustCenterViewer, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUploadedfileMedia implements GetUploadedfileMedia operation.
//
// Download a file from a document.
//
// GET /documents/{documentId}/uploads/{uploadedFileId}/media
func (UnimplementedHandler) GetUploadedfileMedia(ctx context.Context, params GetUploadedfileMediaParams) (r *NodeJSReadableStream, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVendor implements GetVendor operation.
//
// Get a vendor.
//
// GET /vendors/{vendorId}
func (UnimplementedHandler) GetVendor(ctx context.Context, params GetVendorParams) (r *Vendor, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVulnerability implements GetVulnerability operation.
//
// Gets a vulnerability by an ID.
//
// GET /vulnerabilities/{vulnerabilityId}
func (UnimplementedHandler) GetVulnerability(ctx context.Context, params GetVulnerabilityParams) (r *Vulnerability, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVulnerableAsset implements GetVulnerableAsset operation.
//
// Gets a vulnerable asset by ID.
//
// GET /vulnerable-assets/{vulnerableAssetId}
func (UnimplementedHandler) GetVulnerableAsset(ctx context.Context, params GetVulnerableAssetParams) (r *VulnerableAsset, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConnectedIntegrations implements ListConnectedIntegrations operation.
//
// Lists all integrations connected to a Vanta instance.
//
// GET /integrations
func (UnimplementedHandler) ListConnectedIntegrations(ctx context.Context, params ListConnectedIntegrationsParams) (r *PaginatedResponseIntegration, _ error) {
	return r, ht.ErrNotImplemented
}

// ListControls implements ListControls operation.
//
// List controls.
//
// GET /controls
func (UnimplementedHandler) ListControls(ctx context.Context, params ListControlsParams) (r *PaginatedResponseControl, _ error) {
	return r, ht.ErrNotImplemented
}

// ListControlsForDocument implements ListControlsForDocument operation.
//
// List a document's associated controls.
//
// GET /documents/{documentId}/controls
func (UnimplementedHandler) ListControlsForDocument(ctx context.Context, params ListControlsForDocumentParams) (r *PaginatedResponseControl, _ error) {
	return r, ht.ErrNotImplemented
}

// ListControlsForFramework implements ListControlsForFramework operation.
//
// List a framework's controls.
//
// GET /frameworks/{frameworkId}/controls
func (UnimplementedHandler) ListControlsForFramework(ctx context.Context, params ListControlsForFrameworkParams) (r *PaginatedResponseControl, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCustomerTrustAccounts implements ListCustomerTrustAccounts operation.
//
// List customer trust accounts with pagination.
//
// GET /customer-trust/accounts
func (UnimplementedHandler) ListCustomerTrustAccounts(ctx context.Context, params ListCustomerTrustAccountsParams) (r *PaginatedResponseCustomerTrustAccountVantaApi, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiscoveredVendors implements ListDiscoveredVendors operation.
//
// List discovered vendors.
//
// GET /discovered-vendors
func (UnimplementedHandler) ListDiscoveredVendors(ctx context.Context, params ListDiscoveredVendorsParams) (r *PaginatedResponseDiscoveredVendor, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDocuments implements ListDocuments operation.
//
// List documents.
//
// GET /documents
func (UnimplementedHandler) ListDocuments(ctx context.Context, params ListDocumentsParams) (r *PaginatedResponseDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDocumentsForControl implements ListDocumentsForControl operation.
//
// List a control's documents.
//
// GET /controls/{controlId}/documents
func (UnimplementedHandler) ListDocumentsForControl(ctx context.Context, params ListDocumentsForControlParams) (r *PaginatedResponseDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFilesForDocument implements ListFilesForDocument operation.
//
// List the uploaded files for a document.
//
// GET /documents/{documentId}/uploads
func (UnimplementedHandler) ListFilesForDocument(ctx context.Context, params ListFilesForDocumentParams) (r *PaginatedResponseUploadedFileT, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFrameworks implements ListFrameworks operation.
//
// Lists available frameworks.
//
// GET /frameworks
func (UnimplementedHandler) ListFrameworks(ctx context.Context, params ListFrameworksParams) (r *PaginatedResponseFramework, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLibraryControls implements ListLibraryControls operation.
//
// List Vanta controls from the library.
//
// GET /controls/controls-library
func (UnimplementedHandler) ListLibraryControls(ctx context.Context, params ListLibraryControlsParams) (r *PaginatedResponseControl, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLinksForDocument implements ListLinksForDocument operation.
//
// List the uploaded links for a document.
//
// GET /documents/{documentId}/links
func (UnimplementedHandler) ListLinksForDocument(ctx context.Context, params ListLinksForDocumentParams) (r *PaginatedResponseUploadedLink, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMonitoredComputers implements ListMonitoredComputers operation.
//
// Returns a list of computers monitored by an MDM (with an integration built
// by Vanta) or by the Vanta Agent. Currently this list does not include
// resources from partner or customer-built integrations.
//
// GET /monitored-computers
func (UnimplementedHandler) ListMonitoredComputers(ctx context.Context, params ListMonitoredComputersParams) (r *PaginatedResponseMonitoredComputer, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPersonGroups implements ListPersonGroups operation.
//
// Lists all groups by ID.
//
// GET /groups
func (UnimplementedHandler) ListPersonGroups(ctx context.Context, params ListPersonGroupsParams) (r *PaginatedResponseGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPolicies implements ListPolicies operation.
//
// Lists all policies.
//
// GET /policies
func (UnimplementedHandler) ListPolicies(ctx context.Context, params ListPoliciesParams) (r *PaginatedResponsePolicy, _ error) {
	return r, ht.ErrNotImplemented
}

// ListQuestionnaires implements ListQuestionnaires operation.
//
// List questionnaires with filtering and pagination.
//
// GET /customer-trust/questionnaires
func (UnimplementedHandler) ListQuestionnaires(ctx context.Context, params ListQuestionnairesParams) (r *PaginatedResponseCustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// ListResourceKindSummaries implements ListResourceKindSummaries operation.
//
// Lists a connected integration's resource types (kinds) such as S3Bucket or CloudwatchLogGroup.
//
// GET /integrations/{integrationId}/resource-kinds
func (UnimplementedHandler) ListResourceKindSummaries(ctx context.Context, params ListResourceKindSummariesParams) (r []ResourceKindSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRiskScenario implements ListRiskScenario operation.
//
// List risk scenarios.
//
// GET /risk-scenarios
func (UnimplementedHandler) ListRiskScenario(ctx context.Context, params ListRiskScenarioParams) (r *PaginatedResponseRiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTests implements ListTests operation.
//
// Lists all tests based on applied filters.
//
// GET /tests
func (UnimplementedHandler) ListTests(ctx context.Context, params ListTestsParams) (r *PaginatedResponseTest, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTestsForControl implements ListTestsForControl operation.
//
// List a control's tests.
//
// GET /controls/{controlId}/tests
func (UnimplementedHandler) ListTestsForControl(ctx context.Context, params ListTestsForControlParams) (r *PaginatedResponseTest, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterAccessRequests implements ListTrustCenterAccessRequests operation.
//
// Gets a list of access requests for a Trust Center.
//
// GET /trust-centers/{slugId}/access-requests
func (UnimplementedHandler) ListTrustCenterAccessRequests(ctx context.Context, params ListTrustCenterAccessRequestsParams) (r *PaginatedResponseTrustCenterAccessRequest, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterControls implements ListTrustCenterControls operation.
//
// Gets a list of controls on a Trust Center.
//
// GET /trust-centers/{slugId}/controls
func (UnimplementedHandler) ListTrustCenterControls(ctx context.Context, params ListTrustCenterControlsParams) (r *PaginatedResponseTrustCenterControl, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterFaqs implements ListTrustCenterFaqs operation.
//
// Gets a list of FAQs on a Trust Center.
//
// GET /trust-centers/{slugId}/faqs
func (UnimplementedHandler) ListTrustCenterFaqs(ctx context.Context, params ListTrustCenterFaqsParams) (r *ArrayResponseTrustCenterFaq, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterHistoricalAccessRequests implements ListTrustCenterHistoricalAccessRequests operation.
//
// Gets a list of historical (approved or denied) access requests for a Trust Center.
//
// GET /trust-centers/{slugId}/historical-access-requests
func (UnimplementedHandler) ListTrustCenterHistoricalAccessRequests(ctx context.Context, params ListTrustCenterHistoricalAccessRequestsParams) (r *PaginatedResponseTrustCenterAccessRequestHistorical, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterResources implements ListTrustCenterResources operation.
//
// Gets a list of resources on a Trust Center.
//
// GET /trust-centers/{slugId}/resources
func (UnimplementedHandler) ListTrustCenterResources(ctx context.Context, params ListTrustCenterResourcesParams) (r *ArrayResponseTrustCenterResource, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterSubprocessors implements ListTrustCenterSubprocessors operation.
//
// Gets the list of subprocessors on a Trust Center.
//
// GET /trust-centers/{slugId}/subprocessors
func (UnimplementedHandler) ListTrustCenterSubprocessors(ctx context.Context, params ListTrustCenterSubprocessorsParams) (r *ArrayResponseTrustCenterSubprocessor, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterSubscriberGroups implements ListTrustCenterSubscriberGroups operation.
//
// Gets a list of subscriber groups on a Trust Center.
//
// GET /trust-centers/{slugId}/subscriber-groups
func (UnimplementedHandler) ListTrustCenterSubscriberGroups(ctx context.Context, params ListTrustCenterSubscriberGroupsParams) (r *PaginatedResponseTrustCenterSubscriberGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterSubscribers implements ListTrustCenterSubscribers operation.
//
// Gets a list of subscribers on a Trust Center.
//
// GET /trust-centers/{slugId}/subscribers
func (UnimplementedHandler) ListTrustCenterSubscribers(ctx context.Context, params ListTrustCenterSubscribersParams) (r *PaginatedResponseTrustCenterSubscriber, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterUpdates implements ListTrustCenterUpdates operation.
//
// Gets a list of updates on a Trust Center.
//
// GET /trust-centers/{slugId}/updates
func (UnimplementedHandler) ListTrustCenterUpdates(ctx context.Context, params ListTrustCenterUpdatesParams) (r *PaginatedResponseTrustCenterUpdateAPIResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTrustCenterViewers implements ListTrustCenterViewers operation.
//
// Gets a list of viewers that have been granted access to a Trust Center.
//
// GET /trust-centers/{slugId}/viewers
func (UnimplementedHandler) ListTrustCenterViewers(ctx context.Context, params ListTrustCenterViewersParams) (r *PaginatedResponseTrustCenterViewer, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVendorDocuments implements ListVendorDocuments operation.
//
// Returns a vendor's list of documents.
//
// GET /vendors/{vendorId}/documents
func (UnimplementedHandler) ListVendorDocuments(ctx context.Context, params ListVendorDocumentsParams) (r *PaginatedResponseVendorDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVendorFindings implements ListVendorFindings operation.
//
// Lists a vendor's findings.
//
// GET /vendors/{vendorId}/findings
func (UnimplementedHandler) ListVendorFindings(ctx context.Context, params ListVendorFindingsParams) (r *PaginatedResponseVendorFinding, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVendorRiskAttributes implements ListVendorRiskAttributes operation.
//
// Returns a list of vendor risk attributes.
//
// GET /vendor-risk-attributes
func (UnimplementedHandler) ListVendorRiskAttributes(ctx context.Context, params ListVendorRiskAttributesParams) (r *PaginatedResponseVendorRiskAttribute, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVendors implements ListVendors operation.
//
// List of vendors.
//
// GET /vendors
func (UnimplementedHandler) ListVendors(ctx context.Context, params ListVendorsParams) (r *PaginatedResponseVendor, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVulnerabilities implements ListVulnerabilities operation.
//
// List all vulnerabilities based on selected filters.
//
// GET /vulnerabilities
func (UnimplementedHandler) ListVulnerabilities(ctx context.Context, params ListVulnerabilitiesParams) (r *PaginatedResponseVulnerability, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVulnerabilityRemediations implements ListVulnerabilityRemediations operation.
//
// List all vulnerability remediations based on selected filters.
//
// GET /vulnerability-remediations
func (UnimplementedHandler) ListVulnerabilityRemediations(ctx context.Context, params ListVulnerabilityRemediationsParams) (r *PaginatedResponseVulnerabilityRemediation, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVulnerableAssets implements ListVulnerableAssets operation.
//
// List assets that Vanta monitors that are associated with vulnerabilities.
//
// GET /vulnerable-assets
func (UnimplementedHandler) ListVulnerableAssets(ctx context.Context, params ListVulnerableAssetsParams) (r *PaginatedResponseVulnerableAsset, _ error) {
	return r, ht.ErrNotImplemented
}

// ReactivateTestEntity implements ReactivateTestEntity operation.
//
// Reactivates a single tested item (test entity).
// There may be a delay in the reactivation of the test entity until the next test run.
// Use the /vulnerabilities/reactivate endpoint for vulnerabilities.
//
// POST /tests/{testId}/entities/{entityId}/reactivate
func (UnimplementedHandler) ReactivateTestEntity(ctx context.Context, params ReactivateTestEntityParams) error {
	return ht.ErrNotImplemented
}

// RemoveTrustCenterViewer implements RemoveTrustCenterViewer operation.
//
// Revokes a viewer's access to a Trust Center.
//
// DELETE /trust-centers/{slugId}/viewers/{viewerId}
func (UnimplementedHandler) RemoveTrustCenterViewer(ctx context.Context, params RemoveTrustCenterViewerParams) error {
	return ht.ErrNotImplemented
}

// SendNotificationsToAllSubscribers implements SendNotificationsToAllSubscribers operation.
//
// Sends notifications for a specific Trust Center update to all subscribers.
//
// POST /trust-centers/{slugId}/updates/{updateId}/notify-all-subscribers
func (UnimplementedHandler) SendNotificationsToAllSubscribers(ctx context.Context, params SendNotificationsToAllSubscribersParams) error {
	return ht.ErrNotImplemented
}

// SendTrustCenterUpdateNotifications implements SendTrustCenterUpdateNotifications operation.
//
// Sends notifications for a specific Trust Center update to specific subscribers.
// At least one subscriber group or email address is required.
//
// POST /trust-centers/{slugId}/updates/{updateId}/notify-specific-subscribers
func (UnimplementedHandler) SendTrustCenterUpdateNotifications(ctx context.Context, req *SendTrustCenterUpdateNotificationsInput, params SendTrustCenterUpdateNotificationsParams) error {
	return ht.ErrNotImplemented
}

// SetOwnerForControl implements SetOwnerForControl operation.
//
// Assign a control to a user or remove an owner from a control.
//
// POST /controls/{controlId}/set-owner
func (UnimplementedHandler) SetOwnerForControl(ctx context.Context, req *SetOwnerForControlInput, params SetOwnerForControlParams) (r *Control, _ error) {
	return r, ht.ErrNotImplemented
}

// SetOwnerForDocument implements SetOwnerForDocument operation.
//
// Assign or unassign a user to the document.
//
// POST /documents/{documentId}/set-owner
func (UnimplementedHandler) SetOwnerForDocument(ctx context.Context, req *SetOwnerForDocumentInput, params SetOwnerForDocumentParams) (r *Document, _ error) {
	return r, ht.ErrNotImplemented
}

// SetStatusForVendor implements SetStatusForVendor operation.
//
// Sets the status of a vendor, which can be MANAGED, ARCHIVED, or IN_PROCUREMENT.
//
// POST /vendors/{vendorId}/set-status
func (UnimplementedHandler) SetStatusForVendor(ctx context.Context, req *SetStatusForVendorReq, params SetStatusForVendorParams) (r *Vendor, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitDocumentCollection implements SubmitDocumentCollection operation.
//
// Submit document collection.
//
// POST /documents/{documentId}/submit
func (UnimplementedHandler) SubmitDocumentCollection(ctx context.Context, params SubmitDocumentCollectionParams) error {
	return ht.ErrNotImplemented
}

// SubmitRiskForApproval implements SubmitRiskForApproval operation.
//
// Submit a risk scenario for approval.
//
// POST /risk-scenarios/{riskScenarioId}/submit-for-approval
func (UnimplementedHandler) SubmitRiskForApproval(ctx context.Context, req *SubmitRiskForApprovalInput, params SubmitRiskForApprovalParams) (r *RiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateControlMetadata implements UpdateControlMetadata operation.
//
// Update a control's metadata.
//
// PATCH /controls/{controlId}
func (UnimplementedHandler) UpdateControlMetadata(ctx context.Context, req *EditControlMetadataInput, params UpdateControlMetadataParams) (r *Control, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateQuestionnaire implements UpdateQuestionnaire operation.
//
// Update an existing questionnaire.
// Updates one or more fields of a questionnaire.
//
// PATCH /customer-trust/questionnaires/{questionnaireId}
func (UnimplementedHandler) UpdateQuestionnaire(ctx context.Context, req *UpdateQuestionnaireArgs, params UpdateQuestionnaireParams) (r *CustomerTrustQuestionnaire, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateResource implements UpdateResource operation.
//
// Updates metadata for a specific resource such as an S3Bucket or CloudwatchLogGroup.
//
// PATCH /integrations/{integrationId}/resource-kinds/{resourceKind}/resources/{resourceId}
func (UnimplementedHandler) UpdateResource(ctx context.Context, req *UpdateResourceReq, params UpdateResourceParams) error {
	return ht.ErrNotImplemented
}

// UpdateRiskScenario implements UpdateRiskScenario operation.
//
// Update a risk scenario.
//
// PATCH /risk-scenarios/{riskScenarioId}
func (UnimplementedHandler) UpdateRiskScenario(ctx context.Context, req *UpdateRiskScenarioInput, params UpdateRiskScenarioParams) (r *RiskScenario, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterControlCategory implements UpdateTrustCenterControlCategory operation.
//
// Updates a control category on a Trust Center.
//
// PATCH /trust-centers/{slugId}/control-categories/{categoryId}
func (UnimplementedHandler) UpdateTrustCenterControlCategory(ctx context.Context, req *AddOrEditTrustCenterControlCategoryInput, params UpdateTrustCenterControlCategoryParams) (r *TrustCenterControlCategory, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterFaq implements UpdateTrustCenterFaq operation.
//
// Update a specific FAQ on the Trust Center by ID.
//
// PATCH /trust-centers/{slugId}/faqs/{faqId}
func (UnimplementedHandler) UpdateTrustCenterFaq(ctx context.Context, req *AddOrEditTrustCenterFaqInput, params UpdateTrustCenterFaqParams) (r *TrustCenterFaq, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterResource implements UpdateTrustCenterResource operation.
//
// Updates a specific document on a Trust Center.
//
// PATCH /trust-centers/{slugId}/resources/{resourceId}
func (UnimplementedHandler) UpdateTrustCenterResource(ctx context.Context, req *EditTrustCenterResourceInput, params UpdateTrustCenterResourceParams) (r *TrustCenterResource, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterSubprocessor implements UpdateTrustCenterSubprocessor operation.
//
// Updates a subprocessor on a Trust Center.
//
// PATCH /trust-centers/{slugId}/subprocessors/{subprocessorId}
func (UnimplementedHandler) UpdateTrustCenterSubprocessor(ctx context.Context, req *EditTrustCenterSubprocessorInput, params UpdateTrustCenterSubprocessorParams) (r *TrustCenterSubprocessor, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterSubscriberGroup implements UpdateTrustCenterSubscriberGroup operation.
//
// Edits a Trust Center subscriber group.
//
// PATCH /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
func (UnimplementedHandler) UpdateTrustCenterSubscriberGroup(ctx context.Context, req *EditTrustCenterSubscriberGroupInput, params UpdateTrustCenterSubscriberGroupParams) (r *TrustCenterSubscriberGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrustCenterUpdate implements UpdateTrustCenterUpdate operation.
//
// Updates an update on a Trust Center.
//
// PATCH /trust-centers/{slugId}/updates/{updateId}
func (UnimplementedHandler) UpdateTrustCenterUpdate(ctx context.Context, req *EditTrustCenterUpdateInput, params UpdateTrustCenterUpdateParams) (r *TrustCenterUpdateAPIResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateVendor implements UpdateVendor operation.
//
// Update vendor.
//
// PATCH /vendors/{vendorId}
func (UnimplementedHandler) UpdateVendor(ctx context.Context, req *UpdateVendorInput, params UpdateVendorParams) (r *Vendor, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateVendorFinding implements UpdateVendorFinding operation.
//
// Update vendor finding.
//
// PATCH /vendors/{vendorId}/findings/{findingId}
func (UnimplementedHandler) UpdateVendorFinding(ctx context.Context, req *UpdateFindingInput, params UpdateVendorFindingParams) (r *VendorFinding, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadDocumentForSecurityReview implements UploadDocumentForSecurityReview operation.
//
// Add document to a security review.
//
// POST /vendors/{vendorId}/security-reviews/{securityReviewId}/documents
func (UnimplementedHandler) UploadDocumentForSecurityReview(ctx context.Context, req *UploadDocumentForSecurityReviewReq, params UploadDocumentForSecurityReviewParams) (r *VendorDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadDocumentToVendor implements UploadDocumentToVendor operation.
//
// Add document to a vendor.
//
// POST /vendors/{vendorId}/documents
func (UnimplementedHandler) UploadDocumentToVendor(ctx context.Context, req *UploadDocumentToVendorReq, params UploadDocumentToVendorParams) (r *VendorDocument, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadFileForDocument implements UploadFileForDocument operation.
//
// Upload a file for a document.
//
// POST /documents/{documentId}/uploads
func (UnimplementedHandler) UploadFileForDocument(ctx context.Context, req *UploadFileForDocumentReq, params UploadFileForDocumentParams) (r *UploadedFileT, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertGroupsForTrustCenterSubscriber implements UpsertGroupsForTrustCenterSubscriber operation.
//
// Sets groups on a subscriber.
//
// PUT /trust-centers/{slugId}/subscribers/{subscriberId}/groups
func (UnimplementedHandler) UpsertGroupsForTrustCenterSubscriber(ctx context.Context, req *SetGroupsForTrustCenterSubscriberInput, params UpsertGroupsForTrustCenterSubscriberParams) (r *TrustCenterSubscriber, _ error) {
	return r, ht.ErrNotImplemented
}
