// Code generated by ogen, DO NOT EDIT.

package vantaapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddControlFromLibrary implements AddControlFromLibrary operation.
	//
	// Add a control from the Vanta library to your organization's controls.
	//
	// POST /controls/add-from-library
	AddControlFromLibrary(ctx context.Context, req *AddControlFromLibraryInput) (*Control, error)
	// AddControlToTrustCenter implements AddControlToTrustCenter operation.
	//
	// Adds a control to a Trust Center.
	//
	// POST /trust-centers/{slugId}/controls
	AddControlToTrustCenter(ctx context.Context, req *AddControlToTrustCenterInput, params AddControlToTrustCenterParams) (*TrustCenterControl, error)
	// AddDiscoveredVendorToManaged implements AddDiscoveredVendorToManaged operation.
	//
	// Add a discovered vendor to managed vendor.
	//
	// POST /discovered-vendors/{discoveredVendorId}/add-to-managed
	AddDiscoveredVendorToManaged(ctx context.Context, params AddDiscoveredVendorToManagedParams) (*Vendor, error)
	// AddDocumentToControl implements AddDocumentToControl operation.
	//
	// Add a document to a control.
	//
	// POST /controls/{controlId}/add-document-to-control
	AddDocumentToControl(ctx context.Context, req *AddControlDocumentMappingInput, params AddDocumentToControlParams) (*AddDocumentToControlOK, error)
	// AddTestToControl implements AddTestToControl operation.
	//
	// Add a control to test mapping.
	//
	// POST /controls/{controlId}/add-test-to-control
	AddTestToControl(ctx context.Context, req *AddControlTestMappingInput, params AddTestToControlParams) (*AddTestToControlOK, error)
	// AddTrustCenterControlCategory implements AddTrustCenterControlCategory operation.
	//
	// Adds a control category to a Trust Center.
	//
	// POST /trust-centers/{slugId}/control-categories
	AddTrustCenterControlCategory(ctx context.Context, req *AddOrEditTrustCenterControlCategoryInput, params AddTrustCenterControlCategoryParams) (*TrustCenterControlCategory, error)
	// AddTrustCenterViewer implements AddTrustCenterViewer operation.
	//
	// Adds a viewer and grants them access to a Trust Center.
	//
	// POST /trust-centers/{slugId}/viewers
	AddTrustCenterViewer(ctx context.Context, req *AddTrustCenterViewerInput, params AddTrustCenterViewerParams) (*TrustCenterViewer, error)
	// ApproveQuestionnaire implements ApproveQuestionnaire operation.
	//
	// Approve a questionnaire.
	//
	// POST /customer-trust/questionnaires/{questionnaireId}/approve
	ApproveQuestionnaire(ctx context.Context, req *ApproveQuestionnaireRequest, params ApproveQuestionnaireParams) (*CustomerTrustQuestionnaire, error)
	// ApproveTrustCenterAccessRequest implements ApproveTrustCenterAccessRequest operation.
	//
	// Approves an access request on a Trust Center.
	//
	// POST /trust-centers/{slugId}/access-requests/{accessRequestId}/approve
	ApproveTrustCenterAccessRequest(ctx context.Context, req *ApproveTrustCenterAccessRequestInput, params ApproveTrustCenterAccessRequestParams) error
	// CancelRiskScenarioApprovalRequest implements CancelRiskScenarioApprovalRequest operation.
	//
	// Cancel approval request for a risk scenario.
	//
	// POST /risk-scenarios/{riskScenarioId}/cancel-approval-request
	CancelRiskScenarioApprovalRequest(ctx context.Context, params CancelRiskScenarioApprovalRequestParams) (*RiskScenario, error)
	// CompleteQuestionnaire implements CompleteQuestionnaire operation.
	//
	// Complete a questionnaire and optionally sync approved answers to the answer library.
	// Transitions the questionnaire status to COMPLETE. If `shouldSyncApprovedToAnswerLibrary` is true
	// (the default), approved answers are added to the answer library for future use. For
	// non-English SPREADSHEET or DOCUMENT questionnaires, answer library sync will be ignored.
	//
	// POST /customer-trust/questionnaires/{questionnaireId}/complete
	CompleteQuestionnaire(ctx context.Context, req *CompleteQuestionnaireRequest, params CompleteQuestionnaireParams) (*CustomerTrustQuestionnaire, error)
	// CreateCustomerTrustAccount implements CreateCustomerTrustAccount operation.
	//
	// Create a new customer trust account.
	//
	// POST /customer-trust/accounts
	CreateCustomerTrustAccount(ctx context.Context, req *CreateCustomerTrustAccountInput) (*CustomerTrustAccountVantaApi, error)
	// CreateDocument implements CreateDocument operation.
	//
	// Create a custom document.
	//
	// POST /documents
	CreateDocument(ctx context.Context, req *CreateDocumentInput) (*Document, error)
	// CreateFileQuestionnaire implements CreateFileQuestionnaire operation.
	//
	// Create a new file-based questionnaire from an uploaded file (.xlsx, .docx, .pdf).
	//
	// POST /customer-trust/questionnaires/file
	CreateFileQuestionnaire(ctx context.Context, req *CreateFileQuestionnaireReq) (*CustomerTrustQuestionnaire, error)
	// CreateLinkForDocument implements CreateLinkForDocument operation.
	//
	// Create a link for a document.
	//
	// POST /documents/{documentId}/links
	CreateLinkForDocument(ctx context.Context, req *CreateLinkForDocumentInput, params CreateLinkForDocumentParams) (*UploadedLink, error)
	// CreateQuestionnaireExport implements CreateQuestionnaireExport operation.
	//
	// Creates an asynchronous export job for a questionnaire. The export processes in the background
	// and typically completes within a few minutes depending on questionnaire size.
	// Subscribe to the `v1.questionnaire.export-completed` and `v1.questionnaire.export-failed` webhook
	// events to be notified when an export completes or fails.
	// Use the returned `id` with the "getQuestionnaireExport" endpoint to retrieve the download URL once
	// the export completes.
	//
	// POST /customer-trust/questionnaires/exports
	CreateQuestionnaireExport(ctx context.Context, req *CustomerTrustCreateQuestionnaireExportInput) (*CustomerTrustCreateQuestionnaireExportResponse, error)
	// CreateRiskScenario implements CreateRiskScenario operation.
	//
	// Create a new risk scenario.
	//
	// POST /risk-scenarios
	CreateRiskScenario(ctx context.Context, req *CreateRiskScenarioInput) (*RiskScenario, error)
	// CreateTrustCenterFaq implements CreateTrustCenterFaq operation.
	//
	// Adds an FAQ to a Trust Center.
	//
	// POST /trust-centers/{slugId}/faqs
	CreateTrustCenterFaq(ctx context.Context, req *AddOrEditTrustCenterFaqInput, params CreateTrustCenterFaqParams) (*TrustCenterFaq, error)
	// CreateTrustCenterResource implements CreateTrustCenterResource operation.
	//
	// Adds a document to a Trust Center.
	//
	// POST /trust-centers/{slugId}/resources
	CreateTrustCenterResource(ctx context.Context, req *CreateTrustCenterResourceReq, params CreateTrustCenterResourceParams) (*TrustCenterResource, error)
	// CreateTrustCenterSubprocessor implements CreateTrustCenterSubprocessor operation.
	//
	// Adds a subprocessor to a Trust Center.
	//
	// POST /trust-centers/{slugId}/subprocessors
	CreateTrustCenterSubprocessor(ctx context.Context, req *AddTrustCenterSubprocessorInput, params CreateTrustCenterSubprocessorParams) (NilTrustCenterSubprocessor, error)
	// CreateTrustCenterSubscriber implements CreateTrustCenterSubscriber operation.
	//
	// Adds a subscriber to a Trust Center.
	//
	// POST /trust-centers/{slugId}/subscribers
	CreateTrustCenterSubscriber(ctx context.Context, req *AddTrustCenterSubscriberInput, params CreateTrustCenterSubscriberParams) (*TrustCenterSubscriber, error)
	// CreateTrustCenterSubscriberGroup implements CreateTrustCenterSubscriberGroup operation.
	//
	// Adds a subscriber group to a Trust Center.
	//
	// POST /trust-centers/{slugId}/subscriber-groups
	CreateTrustCenterSubscriberGroup(ctx context.Context, req *CreateTrustCenterSubscriberGroupInput, params CreateTrustCenterSubscriberGroupParams) (*TrustCenterSubscriberGroup, error)
	// CreateTrustCenterUpdate implements CreateTrustCenterUpdate operation.
	//
	// Adds an update to a Trust Center.
	//
	// POST /trust-centers/{slugId}/updates
	CreateTrustCenterUpdate(ctx context.Context, req *AddTrustCenterUpdateInput, params CreateTrustCenterUpdateParams) (*TrustCenterUpdateAPIResponse, error)
	// CreateVendor implements CreateVendor operation.
	//
	// Add vendor with metadata.
	//
	// POST /vendors
	CreateVendor(ctx context.Context, req *CreateVendorInput) (*Vendor, error)
	// CreateVendorFinding implements CreateVendorFinding operation.
	//
	// Add vendor finding.
	//
	// POST /vendors/{vendorId}/findings
	CreateVendorFinding(ctx context.Context, req *CreateFindingInput, params CreateVendorFindingParams) (*VendorFinding, error)
	// CreateWebsiteQuestionnaire implements CreateWebsiteQuestionnaire operation.
	//
	// Create a new website-based questionnaire from a portal URL.
	// The portal URL is used to fetch questionnaire content from the target website.
	//
	// POST /customer-trust/questionnaires/website
	CreateWebsiteQuestionnaire(ctx context.Context, req *CreateWebsiteQuestionnaireInput) (*CustomerTrustQuestionnaire, error)
	// DeactivateTestEntity implements DeactivateTestEntity operation.
	//
	// Deactivates a single test item (test entity).
	// There may be a delay in the deactivation of the test entity until the next test run.
	// Use the /vulnerabilities/deactivate endpoint for vulnerabilities.
	//
	// POST /tests/{testId}/entities/{entityId}/deactivate
	DeactivateTestEntity(ctx context.Context, req *DeactivateTestEntityReq, params DeactivateTestEntityParams) error
	// DeleteById implements DeleteById operation.
	//
	// Deletes a vendor.
	//
	// DELETE /vendors/{vendorId}
	DeleteById(ctx context.Context, params DeleteByIdParams) error
	// DeleteControl implements DeleteControl operation.
	//
	// Delete a custom control or move a Vanta control back to the library.
	//
	// DELETE /controls/{controlId}
	DeleteControl(ctx context.Context, params DeleteControlParams) error
	// DeleteDocument implements DeleteDocument operation.
	//
	// Delete a document by ID.
	//
	// DELETE /documents/{documentId}
	DeleteDocument(ctx context.Context, params DeleteDocumentParams) error
	// DeleteDocumentForcontrol implements DeleteDocumentForcontrol operation.
	//
	// Remove a document by ID from a control.
	//
	// DELETE /controls/{controlId}/documents/{documentId}
	DeleteDocumentForcontrol(ctx context.Context, params DeleteDocumentForcontrolParams) error
	// DeleteFileForDocument implements DeleteFileForDocument operation.
	//
	// Delete a file for a document.
	//
	// DELETE /documents/{documentId}/uploads/{uploadedFileId}
	DeleteFileForDocument(ctx context.Context, params DeleteFileForDocumentParams) error
	// DeleteFindingById implements DeleteFindingById operation.
	//
	// Deletes a finding.
	//
	// DELETE /vendors/{vendorId}/findings/{findingId}
	DeleteFindingById(ctx context.Context, params DeleteFindingByIdParams) error
	// DeleteLinkForDocument implements DeleteLinkForDocument operation.
	//
	// Remove a link from a document.
	//
	// DELETE /documents/{documentId}/links/{linkId}
	DeleteLinkForDocument(ctx context.Context, params DeleteLinkForDocumentParams) error
	// DeleteQuestionnaire implements DeleteQuestionnaire operation.
	//
	// Delete a questionnaire by ID.
	//
	// DELETE /customer-trust/questionnaires/{questionnaireId}
	DeleteQuestionnaire(ctx context.Context, params DeleteQuestionnaireParams) error
	// DeleteSecurityReviewDocumentById implements DeleteSecurityReviewDocumentById operation.
	//
	// Delete a security review document.
	//
	// DELETE /vendors/{vendorId}/security-reviews/{securityReviewId}/documents/{documentId}
	DeleteSecurityReviewDocumentById(ctx context.Context, params DeleteSecurityReviewDocumentByIdParams) error
	// DeleteTestForControl implements DeleteTestForControl operation.
	//
	// Remove a control from test mapping.
	//
	// DELETE /controls/{controlId}/tests/{testId}
	DeleteTestForControl(ctx context.Context, params DeleteTestForControlParams) error
	// DeleteTrustCenterControl implements DeleteTrustCenterControl operation.
	//
	// Removes a specific control from a Trust Center. This removes the control
	// from all of the control categories that is in.
	//
	// DELETE /trust-centers/{slugId}/controls/{controlId}
	DeleteTrustCenterControl(ctx context.Context, params DeleteTrustCenterControlParams) error
	// DeleteTrustCenterControlCategory implements DeleteTrustCenterControlCategory operation.
	//
	// Removes a control category from a Trust Center along with all of the
	// controls in the category.
	//
	// DELETE /trust-centers/{slugId}/control-categories/{categoryId}
	DeleteTrustCenterControlCategory(ctx context.Context, params DeleteTrustCenterControlCategoryParams) error
	// DeleteTrustCenterFaq implements DeleteTrustCenterFaq operation.
	//
	// Remove a specific FAQ from the Trust Center by ID.
	//
	// DELETE /trust-centers/{slugId}/faqs/{faqId}
	DeleteTrustCenterFaq(ctx context.Context, params DeleteTrustCenterFaqParams) error
	// DeleteTrustCenterResource implements DeleteTrustCenterResource operation.
	//
	// Removes a specific document from a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/resources/{resourceId}
	DeleteTrustCenterResource(ctx context.Context, params DeleteTrustCenterResourceParams) error
	// DeleteTrustCenterSubprocessor implements DeleteTrustCenterSubprocessor operation.
	//
	// Removes a subprocessor from a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/subprocessors/{subprocessorId}
	DeleteTrustCenterSubprocessor(ctx context.Context, params DeleteTrustCenterSubprocessorParams) error
	// DeleteTrustCenterSubscriber implements DeleteTrustCenterSubscriber operation.
	//
	// Removes a subscriber from a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/subscribers/{subscriberId}
	DeleteTrustCenterSubscriber(ctx context.Context, params DeleteTrustCenterSubscriberParams) error
	// DeleteTrustCenterSubscriberGroup implements DeleteTrustCenterSubscriberGroup operation.
	//
	// Removes a subscriber group from a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
	DeleteTrustCenterSubscriberGroup(ctx context.Context, params DeleteTrustCenterSubscriberGroupParams) error
	// DeleteTrustCenterUpdate implements DeleteTrustCenterUpdate operation.
	//
	// Removes an update from a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/updates/{updateId}
	DeleteTrustCenterUpdate(ctx context.Context, params DeleteTrustCenterUpdateParams) error
	// DenyTrustCenterAccessRequest implements DenyTrustCenterAccessRequest operation.
	//
	// Denies an access request on a Trust Center.
	//
	// POST /trust-centers/{slugId}/access-requests/{accessRequestId}/deny
	DenyTrustCenterAccessRequest(ctx context.Context, params DenyTrustCenterAccessRequestParams) error
	// GetConnectedIntegration implements GetConnectedIntegration operation.
	//
	// Gets details for a specific integration by connection ID.
	//
	// GET /integrations/{integrationId}
	GetConnectedIntegration(ctx context.Context, params GetConnectedIntegrationParams) (*Integration, error)
	// GetControl implements GetControl operation.
	//
	// Get a control by an ID.
	//
	// GET /controls/{controlId}
	GetControl(ctx context.Context, params GetControlParams) (*ControlDetail, error)
	// GetCustomerTrustAccount implements GetCustomerTrustAccount operation.
	//
	// Get a specific customer trust account by ID.
	//
	// GET /customer-trust/accounts/{accountId}
	GetCustomerTrustAccount(ctx context.Context, params GetCustomerTrustAccountParams) (*CustomerTrustAccountVantaApi, error)
	// GetDocument implements GetDocument operation.
	//
	// Get a document by ID.
	//
	// GET /documents/{documentId}
	GetDocument(ctx context.Context, params GetDocumentParams) (*DocumentDetail, error)
	// GetFramework implements GetFramework operation.
	//
	// Get a framework by ID.
	//
	// GET /frameworks/{frameworkId}
	GetFramework(ctx context.Context, params GetFrameworkParams) (*FrameworkDetail, error)
	// GetGroup implements GetGroup operation.
	//
	// Get a group by ID.
	//
	// GET /groups/{groupId}
	GetGroup(ctx context.Context, params GetGroupParams) (*Group, error)
	// GetMonitoredComputer implements GetMonitoredComputer operation.
	//
	// Returns a monitored computer by ID.
	//
	// GET /monitored-computers/{computerId}
	GetMonitoredComputer(ctx context.Context, params GetMonitoredComputerParams) (*MonitoredComputer, error)
	// GetPolicy implements GetPolicy operation.
	//
	// Gets a policy by ID. Policy IDs can be found in Vanta in URL bar after /policies/.
	//
	// GET /policies/{policyId}
	GetPolicy(ctx context.Context, params GetPolicyParams) (*Policy, error)
	// GetQuestionnaire implements GetQuestionnaire operation.
	//
	// Retrieve a questionnaire by ID.
	//
	// GET /customer-trust/questionnaires/{questionnaireId}
	GetQuestionnaire(ctx context.Context, params GetQuestionnaireParams) (*CustomerTrustQuestionnaire, error)
	// GetQuestionnaireExport implements GetQuestionnaireExport operation.
	//
	// Retrieves the current status and result of a questionnaire export using the id received from
	// either the POST /v1/customer-trust/questionnaires/exports endpoint or the v1.questionnaire.
	// export-completed payload.
	// This endpoint utilizes a dynamic response schema that changes based on the value of the status
	// field:
	// - pending: The export is currently in the queue or processing. Only base metadata is returned.
	// - completed: The export finished successfully. The response expands to include completedAt and a
	// downloadUrl. This pre-signed URL is valid for 24 hours; if it expires, simply call this endpoint
	// again to retrieve a fresh, active link.
	// - failed: The process encountered an error. The response expands to include failedAt and an
	// errorMessage detailing the reason for failure.
	// Developers should first check the status string before attempting to access result-specific fields
	// like downloadUrl or errorMessage.
	//
	// GET /customer-trust/questionnaires/exports/{id}
	GetQuestionnaireExport(ctx context.Context, params GetQuestionnaireExportParams) (*CustomerTrustExportStatusResponse, error)
	// GetResourceKindDetails implements GetResourceKindDetails operation.
	//
	// Gets details for a specific resource type (kind) such as S3Bucket or CloudwatchLogGroup.
	//
	// GET /integrations/{integrationId}/resource-kinds/{resourceKind}
	GetResourceKindDetails(ctx context.Context, params GetResourceKindDetailsParams) (*ResourceKindDetails, error)
	// GetRiskScenario implements GetRiskScenario operation.
	//
	// Get a risk scenario by ID (can be the Risk ID or the object ID).
	//
	// GET /risk-scenarios/{riskScenarioId}
	GetRiskScenario(ctx context.Context, params GetRiskScenarioParams) (*RiskScenario, error)
	// GetSecurityReviewDocuments implements GetSecurityReviewDocuments operation.
	//
	// Lists a security review's documents.
	//
	// GET /vendors/{vendorId}/security-reviews/{securityReviewId}/documents
	GetSecurityReviewDocuments(ctx context.Context, params GetSecurityReviewDocumentsParams) (*PaginatedResponseVendorDocument, error)
	// GetSecurityReviewsById implements GetSecurityReviewsById operation.
	//
	// Returns a security review.
	//
	// GET /vendors/{vendorId}/security-reviews/{securityReviewId}
	GetSecurityReviewsById(ctx context.Context, params GetSecurityReviewsByIdParams) (*SecurityReview, error)
	// GetSecurityReviewsByVendorId implements GetSecurityReviewsByVendorId operation.
	//
	// Returns a vendor's security reviews.
	//
	// GET /vendors/{vendorId}/security-reviews
	GetSecurityReviewsByVendorId(ctx context.Context, params GetSecurityReviewsByVendorIdParams) (*PaginatedResponseSecurityReview, error)
	// GetTest implements GetTest operation.
	//
	// Gets a test by ID. Test IDs can be found in Vanta in URL bar after /tests/.
	//
	// GET /tests/{testId}
	GetTest(ctx context.Context, params GetTestParams) (*Test, error)
	// GetTestEntities implements GetTestEntities operation.
	//
	// Gets a list of tested items (entities) for a test by test ID. An entity is a tested item that can
	// have its own outcome.
	// For example, for a test that makes sure that all S3 buckets are versioned, an individual S3 bucket
	// would be an entity.
	//
	// GET /tests/{testId}/entities
	GetTestEntities(ctx context.Context, params GetTestEntitiesParams) (*PaginatedResponseTestResourceEntity, error)
	// GetTrustCenter implements GetTrustCenter operation.
	//
	// Gets a Trust Center by slug ID.
	//
	// GET /trust-centers/{slugId}
	GetTrustCenter(ctx context.Context, params GetTrustCenterParams) (*TrustCenter, error)
	// GetTrustCenterAccessRequest implements GetTrustCenterAccessRequest operation.
	//
	// Gets a specific access request for a Trust Center.
	//
	// GET /trust-centers/{slugId}/access-requests/{accessRequestId}
	GetTrustCenterAccessRequest(ctx context.Context, params GetTrustCenterAccessRequestParams) (*TrustCenterAccessRequest, error)
	// GetTrustCenterControl implements GetTrustCenterControl operation.
	//
	// Gets a specific control on a Trust Center.
	//
	// GET /trust-centers/{slugId}/controls/{controlId}
	GetTrustCenterControl(ctx context.Context, params GetTrustCenterControlParams) (*TrustCenterControl, error)
	// GetTrustCenterControlCategories implements GetTrustCenterControlCategories operation.
	//
	// Gets a list of control categories on a Trust Center.
	//
	// GET /trust-centers/{slugId}/control-categories
	GetTrustCenterControlCategories(ctx context.Context, params GetTrustCenterControlCategoriesParams) (*ArrayResponseTrustCenterControlCategory, error)
	// GetTrustCenterControlCategory implements GetTrustCenterControlCategory operation.
	//
	// Gets a specific control category on a Trust Center.
	//
	// GET /trust-centers/{slugId}/control-categories/{categoryId}
	GetTrustCenterControlCategory(ctx context.Context, params GetTrustCenterControlCategoryParams) (*TrustCenterControlCategory, error)
	// GetTrustCenterFaq implements GetTrustCenterFaq operation.
	//
	// Gets a specific FAQ on the Trust Center by ID.
	//
	// GET /trust-centers/{slugId}/faqs/{faqId}
	GetTrustCenterFaq(ctx context.Context, params GetTrustCenterFaqParams) (*TrustCenterFaq, error)
	// GetTrustCenterResource implements GetTrustCenterResource operation.
	//
	// Gets a specific document on a Trust Center.
	//
	// GET /trust-centers/{slugId}/resources/{resourceId}
	GetTrustCenterResource(ctx context.Context, params GetTrustCenterResourceParams) (*TrustCenterResource, error)
	// GetTrustCenterResourceMedia implements GetTrustCenterResourceMedia operation.
	//
	// Gets the actual given uploaded document for a Trust Center.
	//
	// GET /trust-centers/{slugId}/resources/{resourceId}/media
	GetTrustCenterResourceMedia(ctx context.Context, params GetTrustCenterResourceMediaParams) (*NodeJSReadableStream, error)
	// GetTrustCenterSubprocessor implements GetTrustCenterSubprocessor operation.
	//
	// Gets a specific subprocessor on a Trust Center.
	//
	// GET /trust-centers/{slugId}/subprocessors/{subprocessorId}
	GetTrustCenterSubprocessor(ctx context.Context, params GetTrustCenterSubprocessorParams) (*TrustCenterSubprocessor, error)
	// GetTrustCenterSubscriber implements GetTrustCenterSubscriber operation.
	//
	// Gets a specific subscriber on a Trust Center.
	//
	// GET /trust-centers/{slugId}/subscribers/{subscriberId}
	GetTrustCenterSubscriber(ctx context.Context, params GetTrustCenterSubscriberParams) (*TrustCenterSubscriber, error)
	// GetTrustCenterSubscriberGroup implements GetTrustCenterSubscriberGroup operation.
	//
	// Get a subscriber group by ID.
	//
	// GET /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
	GetTrustCenterSubscriberGroup(ctx context.Context, params GetTrustCenterSubscriberGroupParams) (*TrustCenterSubscriberGroup, error)
	// GetTrustCenterUpdate implements GetTrustCenterUpdate operation.
	//
	// Gets a specific update on a Trust Center.
	//
	// GET /trust-centers/{slugId}/updates/{updateId}
	GetTrustCenterUpdate(ctx context.Context, params GetTrustCenterUpdateParams) (*TrustCenterUpdateAPIResponse, error)
	// GetTrustCenterViewer implements GetTrustCenterViewer operation.
	//
	// Gets a specific viewer for a Trust Center.
	//
	// GET /trust-centers/{slugId}/viewers/{viewerId}
	GetTrustCenterViewer(ctx context.Context, params GetTrustCenterViewerParams) (*TrustCenterViewer, error)
	// GetUploadedfileMedia implements GetUploadedfileMedia operation.
	//
	// Download a file from a document.
	//
	// GET /documents/{documentId}/uploads/{uploadedFileId}/media
	GetUploadedfileMedia(ctx context.Context, params GetUploadedfileMediaParams) (*NodeJSReadableStream, error)
	// GetVendor implements GetVendor operation.
	//
	// Get a vendor.
	//
	// GET /vendors/{vendorId}
	GetVendor(ctx context.Context, params GetVendorParams) (*Vendor, error)
	// GetVulnerability implements GetVulnerability operation.
	//
	// Gets a vulnerability by an ID.
	//
	// GET /vulnerabilities/{vulnerabilityId}
	GetVulnerability(ctx context.Context, params GetVulnerabilityParams) (*Vulnerability, error)
	// GetVulnerableAsset implements GetVulnerableAsset operation.
	//
	// Gets a vulnerable asset by ID.
	//
	// GET /vulnerable-assets/{vulnerableAssetId}
	GetVulnerableAsset(ctx context.Context, params GetVulnerableAssetParams) (*VulnerableAsset, error)
	// ListConnectedIntegrations implements ListConnectedIntegrations operation.
	//
	// Lists all integrations connected to a Vanta instance.
	//
	// GET /integrations
	ListConnectedIntegrations(ctx context.Context, params ListConnectedIntegrationsParams) (*PaginatedResponseIntegration, error)
	// ListControls implements ListControls operation.
	//
	// List controls.
	//
	// GET /controls
	ListControls(ctx context.Context, params ListControlsParams) (*PaginatedResponseControl, error)
	// ListControlsForDocument implements ListControlsForDocument operation.
	//
	// List a document's associated controls.
	//
	// GET /documents/{documentId}/controls
	ListControlsForDocument(ctx context.Context, params ListControlsForDocumentParams) (*PaginatedResponseControl, error)
	// ListControlsForFramework implements ListControlsForFramework operation.
	//
	// List a framework's controls.
	//
	// GET /frameworks/{frameworkId}/controls
	ListControlsForFramework(ctx context.Context, params ListControlsForFrameworkParams) (*PaginatedResponseControl, error)
	// ListCustomerTrustAccounts implements ListCustomerTrustAccounts operation.
	//
	// List customer trust accounts with pagination.
	//
	// GET /customer-trust/accounts
	ListCustomerTrustAccounts(ctx context.Context, params ListCustomerTrustAccountsParams) (*PaginatedResponseCustomerTrustAccountVantaApi, error)
	// ListDiscoveredVendors implements ListDiscoveredVendors operation.
	//
	// List discovered vendors.
	//
	// GET /discovered-vendors
	ListDiscoveredVendors(ctx context.Context, params ListDiscoveredVendorsParams) (*PaginatedResponseDiscoveredVendor, error)
	// ListDocuments implements ListDocuments operation.
	//
	// List documents.
	//
	// GET /documents
	ListDocuments(ctx context.Context, params ListDocumentsParams) (*PaginatedResponseDocument, error)
	// ListDocumentsForControl implements ListDocumentsForControl operation.
	//
	// List a control's documents.
	//
	// GET /controls/{controlId}/documents
	ListDocumentsForControl(ctx context.Context, params ListDocumentsForControlParams) (*PaginatedResponseDocument, error)
	// ListFilesForDocument implements ListFilesForDocument operation.
	//
	// List the uploaded files for a document.
	//
	// GET /documents/{documentId}/uploads
	ListFilesForDocument(ctx context.Context, params ListFilesForDocumentParams) (*PaginatedResponseUploadedFileT, error)
	// ListFrameworks implements ListFrameworks operation.
	//
	// Lists available frameworks.
	//
	// GET /frameworks
	ListFrameworks(ctx context.Context, params ListFrameworksParams) (*PaginatedResponseFramework, error)
	// ListLibraryControls implements ListLibraryControls operation.
	//
	// List Vanta controls from the library.
	//
	// GET /controls/controls-library
	ListLibraryControls(ctx context.Context, params ListLibraryControlsParams) (*PaginatedResponseControl, error)
	// ListLinksForDocument implements ListLinksForDocument operation.
	//
	// List the uploaded links for a document.
	//
	// GET /documents/{documentId}/links
	ListLinksForDocument(ctx context.Context, params ListLinksForDocumentParams) (*PaginatedResponseUploadedLink, error)
	// ListMonitoredComputers implements ListMonitoredComputers operation.
	//
	// Returns a list of computers monitored by an MDM (with an integration built
	// by Vanta) or by the Vanta Agent. Currently this list does not include
	// resources from partner or customer-built integrations.
	//
	// GET /monitored-computers
	ListMonitoredComputers(ctx context.Context, params ListMonitoredComputersParams) (*PaginatedResponseMonitoredComputer, error)
	// ListPersonGroups implements ListPersonGroups operation.
	//
	// Lists all groups by ID.
	//
	// GET /groups
	ListPersonGroups(ctx context.Context, params ListPersonGroupsParams) (*PaginatedResponseGroup, error)
	// ListPolicies implements ListPolicies operation.
	//
	// Lists all policies.
	//
	// GET /policies
	ListPolicies(ctx context.Context, params ListPoliciesParams) (*PaginatedResponsePolicy, error)
	// ListQuestionnaires implements ListQuestionnaires operation.
	//
	// List questionnaires with filtering and pagination.
	//
	// GET /customer-trust/questionnaires
	ListQuestionnaires(ctx context.Context, params ListQuestionnairesParams) (*PaginatedResponseCustomerTrustQuestionnaire, error)
	// ListResourceKindSummaries implements ListResourceKindSummaries operation.
	//
	// Lists a connected integration's resource types (kinds) such as S3Bucket or CloudwatchLogGroup.
	//
	// GET /integrations/{integrationId}/resource-kinds
	ListResourceKindSummaries(ctx context.Context, params ListResourceKindSummariesParams) ([]ResourceKindSummary, error)
	// ListRiskScenario implements ListRiskScenario operation.
	//
	// List risk scenarios.
	//
	// GET /risk-scenarios
	ListRiskScenario(ctx context.Context, params ListRiskScenarioParams) (*PaginatedResponseRiskScenario, error)
	// ListTests implements ListTests operation.
	//
	// Lists all tests based on applied filters.
	//
	// GET /tests
	ListTests(ctx context.Context, params ListTestsParams) (*PaginatedResponseTest, error)
	// ListTestsForControl implements ListTestsForControl operation.
	//
	// List a control's tests.
	//
	// GET /controls/{controlId}/tests
	ListTestsForControl(ctx context.Context, params ListTestsForControlParams) (*PaginatedResponseTest, error)
	// ListTrustCenterAccessRequests implements ListTrustCenterAccessRequests operation.
	//
	// Gets a list of access requests for a Trust Center.
	//
	// GET /trust-centers/{slugId}/access-requests
	ListTrustCenterAccessRequests(ctx context.Context, params ListTrustCenterAccessRequestsParams) (*PaginatedResponseTrustCenterAccessRequest, error)
	// ListTrustCenterControls implements ListTrustCenterControls operation.
	//
	// Gets a list of controls on a Trust Center.
	//
	// GET /trust-centers/{slugId}/controls
	ListTrustCenterControls(ctx context.Context, params ListTrustCenterControlsParams) (*PaginatedResponseTrustCenterControl, error)
	// ListTrustCenterFaqs implements ListTrustCenterFaqs operation.
	//
	// Gets a list of FAQs on a Trust Center.
	//
	// GET /trust-centers/{slugId}/faqs
	ListTrustCenterFaqs(ctx context.Context, params ListTrustCenterFaqsParams) (*ArrayResponseTrustCenterFaq, error)
	// ListTrustCenterHistoricalAccessRequests implements ListTrustCenterHistoricalAccessRequests operation.
	//
	// Gets a list of historical (approved or denied) access requests for a Trust Center.
	//
	// GET /trust-centers/{slugId}/historical-access-requests
	ListTrustCenterHistoricalAccessRequests(ctx context.Context, params ListTrustCenterHistoricalAccessRequestsParams) (*PaginatedResponseTrustCenterAccessRequestHistorical, error)
	// ListTrustCenterResources implements ListTrustCenterResources operation.
	//
	// Gets a list of resources on a Trust Center.
	//
	// GET /trust-centers/{slugId}/resources
	ListTrustCenterResources(ctx context.Context, params ListTrustCenterResourcesParams) (*ArrayResponseTrustCenterResource, error)
	// ListTrustCenterSubprocessors implements ListTrustCenterSubprocessors operation.
	//
	// Gets the list of subprocessors on a Trust Center.
	//
	// GET /trust-centers/{slugId}/subprocessors
	ListTrustCenterSubprocessors(ctx context.Context, params ListTrustCenterSubprocessorsParams) (*ArrayResponseTrustCenterSubprocessor, error)
	// ListTrustCenterSubscriberGroups implements ListTrustCenterSubscriberGroups operation.
	//
	// Gets a list of subscriber groups on a Trust Center.
	//
	// GET /trust-centers/{slugId}/subscriber-groups
	ListTrustCenterSubscriberGroups(ctx context.Context, params ListTrustCenterSubscriberGroupsParams) (*PaginatedResponseTrustCenterSubscriberGroup, error)
	// ListTrustCenterSubscribers implements ListTrustCenterSubscribers operation.
	//
	// Gets a list of subscribers on a Trust Center.
	//
	// GET /trust-centers/{slugId}/subscribers
	ListTrustCenterSubscribers(ctx context.Context, params ListTrustCenterSubscribersParams) (*PaginatedResponseTrustCenterSubscriber, error)
	// ListTrustCenterUpdates implements ListTrustCenterUpdates operation.
	//
	// Gets a list of updates on a Trust Center.
	//
	// GET /trust-centers/{slugId}/updates
	ListTrustCenterUpdates(ctx context.Context, params ListTrustCenterUpdatesParams) (*PaginatedResponseTrustCenterUpdateAPIResponse, error)
	// ListTrustCenterViewers implements ListTrustCenterViewers operation.
	//
	// Gets a list of viewers that have been granted access to a Trust Center.
	//
	// GET /trust-centers/{slugId}/viewers
	ListTrustCenterViewers(ctx context.Context, params ListTrustCenterViewersParams) (*PaginatedResponseTrustCenterViewer, error)
	// ListVendorDocuments implements ListVendorDocuments operation.
	//
	// Returns a vendor's list of documents.
	//
	// GET /vendors/{vendorId}/documents
	ListVendorDocuments(ctx context.Context, params ListVendorDocumentsParams) (*PaginatedResponseVendorDocument, error)
	// ListVendorFindings implements ListVendorFindings operation.
	//
	// Lists a vendor's findings.
	//
	// GET /vendors/{vendorId}/findings
	ListVendorFindings(ctx context.Context, params ListVendorFindingsParams) (*PaginatedResponseVendorFinding, error)
	// ListVendorRiskAttributes implements ListVendorRiskAttributes operation.
	//
	// Returns a list of vendor risk attributes.
	//
	// GET /vendor-risk-attributes
	ListVendorRiskAttributes(ctx context.Context, params ListVendorRiskAttributesParams) (*PaginatedResponseVendorRiskAttribute, error)
	// ListVendors implements ListVendors operation.
	//
	// List of vendors.
	//
	// GET /vendors
	ListVendors(ctx context.Context, params ListVendorsParams) (*PaginatedResponseVendor, error)
	// ListVulnerabilities implements ListVulnerabilities operation.
	//
	// List all vulnerabilities based on selected filters.
	//
	// GET /vulnerabilities
	ListVulnerabilities(ctx context.Context, params ListVulnerabilitiesParams) (*PaginatedResponseVulnerability, error)
	// ListVulnerabilityRemediations implements ListVulnerabilityRemediations operation.
	//
	// List all vulnerability remediations based on selected filters.
	//
	// GET /vulnerability-remediations
	ListVulnerabilityRemediations(ctx context.Context, params ListVulnerabilityRemediationsParams) (*PaginatedResponseVulnerabilityRemediation, error)
	// ListVulnerableAssets implements ListVulnerableAssets operation.
	//
	// List assets that Vanta monitors that are associated with vulnerabilities.
	//
	// GET /vulnerable-assets
	ListVulnerableAssets(ctx context.Context, params ListVulnerableAssetsParams) (*PaginatedResponseVulnerableAsset, error)
	// ReactivateTestEntity implements ReactivateTestEntity operation.
	//
	// Reactivates a single tested item (test entity).
	// There may be a delay in the reactivation of the test entity until the next test run.
	// Use the /vulnerabilities/reactivate endpoint for vulnerabilities.
	//
	// POST /tests/{testId}/entities/{entityId}/reactivate
	ReactivateTestEntity(ctx context.Context, params ReactivateTestEntityParams) error
	// RemoveTrustCenterViewer implements RemoveTrustCenterViewer operation.
	//
	// Revokes a viewer's access to a Trust Center.
	//
	// DELETE /trust-centers/{slugId}/viewers/{viewerId}
	RemoveTrustCenterViewer(ctx context.Context, params RemoveTrustCenterViewerParams) error
	// SendNotificationsToAllSubscribers implements SendNotificationsToAllSubscribers operation.
	//
	// Sends notifications for a specific Trust Center update to all subscribers.
	//
	// POST /trust-centers/{slugId}/updates/{updateId}/notify-all-subscribers
	SendNotificationsToAllSubscribers(ctx context.Context, params SendNotificationsToAllSubscribersParams) error
	// SendTrustCenterUpdateNotifications implements SendTrustCenterUpdateNotifications operation.
	//
	// Sends notifications for a specific Trust Center update to specific subscribers.
	// At least one subscriber group or email address is required.
	//
	// POST /trust-centers/{slugId}/updates/{updateId}/notify-specific-subscribers
	SendTrustCenterUpdateNotifications(ctx context.Context, req *SendTrustCenterUpdateNotificationsInput, params SendTrustCenterUpdateNotificationsParams) error
	// SetOwnerForControl implements SetOwnerForControl operation.
	//
	// Assign a control to a user or remove an owner from a control.
	//
	// POST /controls/{controlId}/set-owner
	SetOwnerForControl(ctx context.Context, req *SetOwnerForControlInput, params SetOwnerForControlParams) (*Control, error)
	// SetOwnerForDocument implements SetOwnerForDocument operation.
	//
	// Assign or unassign a user to the document.
	//
	// POST /documents/{documentId}/set-owner
	SetOwnerForDocument(ctx context.Context, req *SetOwnerForDocumentInput, params SetOwnerForDocumentParams) (*Document, error)
	// SetStatusForVendor implements SetStatusForVendor operation.
	//
	// Sets the status of a vendor, which can be MANAGED, ARCHIVED, or IN_PROCUREMENT.
	//
	// POST /vendors/{vendorId}/set-status
	SetStatusForVendor(ctx context.Context, req *SetStatusForVendorReq, params SetStatusForVendorParams) (*Vendor, error)
	// SubmitDocumentCollection implements SubmitDocumentCollection operation.
	//
	// Submit document collection.
	//
	// POST /documents/{documentId}/submit
	SubmitDocumentCollection(ctx context.Context, params SubmitDocumentCollectionParams) error
	// SubmitRiskForApproval implements SubmitRiskForApproval operation.
	//
	// Submit a risk scenario for approval.
	//
	// POST /risk-scenarios/{riskScenarioId}/submit-for-approval
	SubmitRiskForApproval(ctx context.Context, req *SubmitRiskForApprovalInput, params SubmitRiskForApprovalParams) (*RiskScenario, error)
	// UpdateControlMetadata implements UpdateControlMetadata operation.
	//
	// Update a control's metadata.
	//
	// PATCH /controls/{controlId}
	UpdateControlMetadata(ctx context.Context, req *EditControlMetadataInput, params UpdateControlMetadataParams) (*Control, error)
	// UpdateQuestionnaire implements UpdateQuestionnaire operation.
	//
	// Update an existing questionnaire.
	// Updates one or more fields of a questionnaire.
	//
	// PATCH /customer-trust/questionnaires/{questionnaireId}
	UpdateQuestionnaire(ctx context.Context, req *UpdateQuestionnaireArgs, params UpdateQuestionnaireParams) (*CustomerTrustQuestionnaire, error)
	// UpdateResource implements UpdateResource operation.
	//
	// Updates metadata for a specific resource such as an S3Bucket or CloudwatchLogGroup.
	//
	// PATCH /integrations/{integrationId}/resource-kinds/{resourceKind}/resources/{resourceId}
	UpdateResource(ctx context.Context, req *UpdateResourceReq, params UpdateResourceParams) error
	// UpdateRiskScenario implements UpdateRiskScenario operation.
	//
	// Update a risk scenario.
	//
	// PATCH /risk-scenarios/{riskScenarioId}
	UpdateRiskScenario(ctx context.Context, req *UpdateRiskScenarioInput, params UpdateRiskScenarioParams) (*RiskScenario, error)
	// UpdateTrustCenterControlCategory implements UpdateTrustCenterControlCategory operation.
	//
	// Updates a control category on a Trust Center.
	//
	// PATCH /trust-centers/{slugId}/control-categories/{categoryId}
	UpdateTrustCenterControlCategory(ctx context.Context, req *AddOrEditTrustCenterControlCategoryInput, params UpdateTrustCenterControlCategoryParams) (*TrustCenterControlCategory, error)
	// UpdateTrustCenterFaq implements UpdateTrustCenterFaq operation.
	//
	// Update a specific FAQ on the Trust Center by ID.
	//
	// PATCH /trust-centers/{slugId}/faqs/{faqId}
	UpdateTrustCenterFaq(ctx context.Context, req *AddOrEditTrustCenterFaqInput, params UpdateTrustCenterFaqParams) (*TrustCenterFaq, error)
	// UpdateTrustCenterResource implements UpdateTrustCenterResource operation.
	//
	// Updates a specific document on a Trust Center.
	//
	// PATCH /trust-centers/{slugId}/resources/{resourceId}
	UpdateTrustCenterResource(ctx context.Context, req *EditTrustCenterResourceInput, params UpdateTrustCenterResourceParams) (*TrustCenterResource, error)
	// UpdateTrustCenterSubprocessor implements UpdateTrustCenterSubprocessor operation.
	//
	// Updates a subprocessor on a Trust Center.
	//
	// PATCH /trust-centers/{slugId}/subprocessors/{subprocessorId}
	UpdateTrustCenterSubprocessor(ctx context.Context, req *EditTrustCenterSubprocessorInput, params UpdateTrustCenterSubprocessorParams) (*TrustCenterSubprocessor, error)
	// UpdateTrustCenterSubscriberGroup implements UpdateTrustCenterSubscriberGroup operation.
	//
	// Edits a Trust Center subscriber group.
	//
	// PATCH /trust-centers/{slugId}/subscriber-groups/{subscriberGroupId}
	UpdateTrustCenterSubscriberGroup(ctx context.Context, req *EditTrustCenterSubscriberGroupInput, params UpdateTrustCenterSubscriberGroupParams) (*TrustCenterSubscriberGroup, error)
	// UpdateTrustCenterUpdate implements UpdateTrustCenterUpdate operation.
	//
	// Updates an update on a Trust Center.
	//
	// PATCH /trust-centers/{slugId}/updates/{updateId}
	UpdateTrustCenterUpdate(ctx context.Context, req *EditTrustCenterUpdateInput, params UpdateTrustCenterUpdateParams) (*TrustCenterUpdateAPIResponse, error)
	// UpdateVendor implements UpdateVendor operation.
	//
	// Update vendor.
	//
	// PATCH /vendors/{vendorId}
	UpdateVendor(ctx context.Context, req *UpdateVendorInput, params UpdateVendorParams) (*Vendor, error)
	// UpdateVendorFinding implements UpdateVendorFinding operation.
	//
	// Update vendor finding.
	//
	// PATCH /vendors/{vendorId}/findings/{findingId}
	UpdateVendorFinding(ctx context.Context, req *UpdateFindingInput, params UpdateVendorFindingParams) (*VendorFinding, error)
	// UploadDocumentForSecurityReview implements UploadDocumentForSecurityReview operation.
	//
	// Add document to a security review.
	//
	// POST /vendors/{vendorId}/security-reviews/{securityReviewId}/documents
	UploadDocumentForSecurityReview(ctx context.Context, req *UploadDocumentForSecurityReviewReq, params UploadDocumentForSecurityReviewParams) (*VendorDocument, error)
	// UploadDocumentToVendor implements UploadDocumentToVendor operation.
	//
	// Add document to a vendor.
	//
	// POST /vendors/{vendorId}/documents
	UploadDocumentToVendor(ctx context.Context, req *UploadDocumentToVendorReq, params UploadDocumentToVendorParams) (*VendorDocument, error)
	// UploadFileForDocument implements UploadFileForDocument operation.
	//
	// Upload a file for a document.
	//
	// POST /documents/{documentId}/uploads
	UploadFileForDocument(ctx context.Context, req *UploadFileForDocumentReq, params UploadFileForDocumentParams) (*UploadedFileT, error)
	// UpsertGroupsForTrustCenterSubscriber implements UpsertGroupsForTrustCenterSubscriber operation.
	//
	// Sets groups on a subscriber.
	//
	// PUT /trust-centers/{slugId}/subscribers/{subscriberId}/groups
	UpsertGroupsForTrustCenterSubscriber(ctx context.Context, req *SetGroupsForTrustCenterSubscriberInput, params UpsertGroupsForTrustCenterSubscriberParams) (*TrustCenterSubscriber, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
